### ISSUE TITLE
Streak not counting correctly

### ISSUE THREAD

**Issue by tomy0000000** [DenverCoder1/github-readme-streak-stats#107]
**Describe the bug**
Streak not counting correctly

**Screenshots**
![截圖 2021-07-05 上午12 55 18](https://user-images.githubusercontent.com/23290356/124393161-c5651380-dd2b-11eb-8c9c-5ab97e346d57.png)
![截圖 2021-07-05 上午12 56 26](https://user-images.githubusercontent.com/23290356/124393191-d877e380-dd2b-11eb-9d57-5b61e972ef9b.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 91.0.4472.114

**Additional context**
Sometimes I commit to a repo locally, but push to few days after. I wonder if that's gonna affect the stats counting.

**Comment by tomy0000000** [comment]
Possible duplicate of #83, but I don't think I have any future commit.

**Comment by DenverCoder1** [comment]
Your profile shows you have no contributions on June 26

![image](https://user-images.githubusercontent.com/20955511/124467948-3266c080-dda1-11eb-86fc-742cceb96b7c.png)

You may need to change your contribution settings to include private repositories

**Comment by DenverCoder1** [comment]
> Sometimes I commit to a repo locally, but push to few days after. I wonder if that's gonna affect the stats counting

The streak works the same way as the contribution graph, when you push to the main branch, it will retroactively count as a contribution for the day that the commit was made.

**Comment by tomy0000000** [comment]
Hmm... that's weird, it does show that I have reviewed a [pull requests](https://github.com/tomy0000000/Tubee/pull/76) (in a public repo) on Jun 26.

![PixelSnap 2021-07-05 at 22 05 36](https://user-images.githubusercontent.com/23290356/124483762-48927200-dddd-11eb-9b38-2d104c256355.png)

Is it because of timezone?

In GMT+8 (My Timezone), my contribution:
* Review PR: Jun 26, 2:36 AM
* Commit: Jun 27, 11:23 PM

say the timezone is shifted to GMT+0, that will be:
* Review PR: Jun 25, 18:36 PM
* Commit: Jun 27, 3:23 PM

there's the gap.

**Comment by DenverCoder1** [comment]
It's possible, although even if I change my computer's timezone it doesn't seem to change.

When I look at it, it shows up as June 25.

![image](https://user-images.githubusercontent.com/20955511/124489988-436ffb80-ddba-11eb-97b3-260eb325907f.png)

**Comment by DenverCoder1** [comment]
Streak stats relies on GitHub's charts for info, so it will have an issue if the green squares have an issue.

If you don't think that date should break the streak, you can adjust the dates of the commits through the command line with `amend` or create a new commit with the `--date` flag (eg. `git commit --date "Sat Jun 26 12:00 2021 +0000"`).

**Comment by tomy0000000** [comment]
Well I guess that's a no fix then, but at least I know why now.
Thanks for help clarification
