### ISSUE TITLE
Add `date_format` to the demo site

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-streak-stats#134]
This issue requires HTML. The code will go in [index.php](https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/src/demo/index.php), but you do not need to know PHP for adding this.

**Is your feature request related to a problem? Please describe.**
The demo site does not currently have a field for customizing the date format

**Describe the solution you'd like**
Add a text input field for the user to enter one

**Additional context**
The default value is `M j[, Y]`

Please see [Date Formats](https://github.com/DenverCoder1/github-readme-streak-stats#date-formats) in the readme for more details about how it works.

Optional: include a tooltip or link where users can read more info on how to use the property.

**Comment by lucid-dreem** [comment]
I can work on this issue! Just clarifying, would this require a text input field or a dropdown menu for the different options that are mentioned in the README?

**Comment by DenverCoder1** [comment]
@lucid-dreem I was originally thinking a text input since it can be customized to anything that can be done with [PHP date format characters](https://www.php.net/manual/en/datetime.format.php).

It might be an easier user experience to give them a few common options to choose from, though.

I think I can leave it up to you to decide.
