### ISSUE TITLE
Add ability to set the output type to PNG

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-streak-stats#135]
It may be useful to be able to directly get a PNG versions of the streak stats cards.

One way this can be done is by converting the SVG output to a PNG.

If necessary, ImageMagick or a similar library may be used to do this.

You may need the animations to be stripped out of the SVG before conversion.

You may use [this script](https://gist.github.com/DenverCoder1/955096c0d458e63016fc397c3e8d0edf) (written in Python) for inspiration. Since this project is written in PHP it would be preferable for the solution to this issue to be written in PHP.

There is currently a `type` option allowing output as `svg` or `json`, this can be added as a 3rd option.

**Comment by Rocksheep** [comment]
Hi, do you mind if I pick this one up?

**Comment by DenverCoder1** [comment]
@Rocksheep Sure, that would be awesome!
