### ISSUE TITLE
Hide FF at end of colors on the demo site

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-streak-stats#136]
This issue is to be done in JavaScript.

On the demo site in the advanced options, you can choose colors with a color-picker.

Since it supports transparency all colors are 8 hex digits (with the last 2 representing the transparency)

If there is full opacity, the last two characters will be FF and the FF is optional.

## Feature suggestion

Make the input box automatically remove the FF from the input value whenever the color is changed and the color ends with FF.

## Example

If you select the color like this:

![1](https://i.imgur.com/zqhFokf.png)

It should get automatically changed to this when you click away:

![2](https://i.imgur.com/u3zgu99.png)

Let me know if you get stuck or have any questions.

**Comment by m1ga** [comment]
I can work on this issue

**Comment by DenverCoder1** [comment]
@m1ga That would be great!
