### ISSUE TITLE
Output errors as JSON when type is set to `json`

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-streak-stats#141]
Currently there is an option to set the output type to JSON to get stats in JSON format.

Example: https://github-readme-streak-stats.herokuapp.com/?user=DenverCoder1&type=json

If there is an error (eg. invalid username, etc.), currently the error card in SVG gets displayed.

It may be best if instead of returning the SVG it echos the response in JSON format, for example:

```json
{
    "error": "User could not be found."
}
```

**Note:** It may be advisable to wait for #140 to be merged before starting in order to avoid merge conflicts.

**Comment by menghif** [comment]
Hi, I would like to work on this. I can wait for #140 to be merged.

**Comment by DenverCoder1** [comment]
@menghif That's great! If you have any questions feel free to ask!

**Comment by DenverCoder1** [comment]
@menghif 140 is merged already, feel free to start whenever if you haven't already :)
