### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by Evavic44** [DenverCoder1/github-readme-streak-stats#143]
## **Is your feature request related to a problem? Please describe.**
No

## **Describe the solution you'd like**
Add a favicon to the demo site

**Comment by DenverCoder1** [comment]
Great idea!

**Comment by Lilfaen** [comment]
I would love to work on this one, if it's okay with you!

**Comment by DenverCoder1** [comment]
@Lilfaen Sounds good! If you have any questions feel free to ask. I'm thinking it could be like a fire emoji, Twemoji is 100% free to use so we could use theirs. If you think you can make it even better, go for it :+1:

**Comment by Lilfaen** [comment]
@DenverCoder1 Lovely, I would've converted the fire icon that is already in use:

![icon](https://user-images.githubusercontent.com/39119695/135753426-e906d9e1-835f-40d6-a62d-8143b0cb4494.png)

**Comment by DenverCoder1** [comment]
@Lilfaen Sounds good. Either way is fine. Whatever you think looks better.
