### ISSUE TITLE
Add button for exporting a theme from the demo site

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-streak-stats#144]
The demo site could benefit from an option that allows you to export a theme to PHP code with the click of a button.

The button would only need to show up if the user has changed the theme colors in the advanced options.

The output may look something like this:

```php
[
    "background" => "#020200",
    "border" => "#a8a8a8",
    "stroke" => "#a8a8a8",
    "ring" => "#e41d44",
    "fire" => "#e41d44",
    "currStreakNum" => "#f9dd3c",
    "currStreakLabel" => "#f9dd3c",
    "sideNums" => "#5cadc0",
    "sideLabels" => "#5cadc0",
    "dates" => "#ed7b25",
]
```

There should be a button to copy the array to the clipboard.

The idea is to make it easier to contribute to [themes.php](https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/src/themes.php)

**Comment by komen205** [comment]
I can try this :)

**Comment by DenverCoder1** [comment]
@komen205 Great! If you have any questions, feel free to ask.
