### ISSUE TITLE
Color picker adds `FF` when colors are typed into the color picker

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-streak-stats#145]
**Describe the bug**
Color picker adds `FF` (representing full opacity) to 6-digit colors that are pasted from the clipboard or colors that were edited by typing digits.

**To Reproduce**
1. Go to the demo site
2. Click on advanced options
3. Add an option
4. Click the color picker
5. Paste a 6-digit color (eg. `#F7DF1E`) in the box or change a digit by overwriting the character
6. Notice that `FF` gets added to the end when this should only appear for partially transparent colors.

**Expected behavior**
The `FF` should not appear since the color is meant to be fully opaque.

**Screenshots**

![Peek 2021-10-03 09-44](https://user-images.githubusercontent.com/20955511/135743182-c92a3b70-7444-4bce-b1d8-642d6281d8f8.gif)

**Desktop (please complete the following information):**
- OS: Arch Linux
- Browser Brave
- Version 1.30.86 Chromium: 94.0.4606.61 (Official Build) (64-bit)

**Comment by Rocksheep** [comment]
I'll have a go at this bug, if you don't mind.

**Comment by DenverCoder1** [comment]
@Rocksheep Great!
