### ISSUE TITLE
PNG endpoint not working on Heroku

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-streak-stats#149]
If anyone has ideas on how to fix this server error on Heroku let me know

```
heroku[router]: at=info method=GET path="/?user=denvercoder1&type=png" host=github-readme-streak-stats.herokuapp.com request_id=57a0d837-7f0a-4edd-b69e-3e24cee3193f fwd="185.191.205.141" dyno=web.1 connect=8ms service=395ms status=500 bytes=315 protocol=https
app[web.1]: [03-Oct-2021 13:02:55 UTC] PHP Fatal error:  Uncaught ImagickException: no decode delegate for this image format `' @ error/blob.c/BlobToImage/353 in /app/src/card.php:325
app[web.1]: Stack trace:
app[web.1]: #0 /app/src/card.php(325): Imagick->readImageBlob()
app[web.1]: #1 /app/src/index.php(70): echoAsPng()
app[web.1]: #2 {main}
app[web.1]:   thrown in /app/src/card.php on line 325
app[web.1]: 10.1.4.157 - - [03/Oct/2021:13:02:55 +0000] "GET /?user=denvercoder1&type=png HTTP/1.1" 500 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
```

**Comment by Rocksheep** [comment]
Oh I've seen this error before while I was working on the code, so I may know how to fix it.

**Comment by Rocksheep** [comment]
I see that you've reopened this. Are you still getting the same error message?

**Comment by DenverCoder1** [comment]
@Rocksheep Yeah, still getting this error. Might have something to do with Heroku.

```
at=info method=GET path="/?user=DenverCoder1&type=png" host=github-readme-streak-stats.herokuapp.com request_id=02523d0e-fde5-450d-8fb3-710c1438cdf9 fwd="185.191.205.141" dyno=web.1 connect=0ms service=113ms status=500 bytes=315 protocol=https
[03-Oct-2021 16:33:22 UTC] PHP Fatal error:  Uncaught ImagickException: no decode delegate for this image format `' @ error/blob.c/BlobToImage/353 in /app/src/card.php:328
Stack trace:
#0 /app/src/card.php(328): Imagick->readImageBlob()
#1 /app/src/index.php(70): echoAsPng()
#2 {main}
  thrown in /app/src/card.php on line 328
10.1.54.146 - - [03/Oct/2021:16:33:21 +0000] "GET /?user=DenverCoder1&type=png HTTP/1.1" 500 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
```

**Comment by Rocksheep** [comment]
It looks like it's not recognising the SVG as an SVG... Can you give me the version of PHP and imagick that the Heroku instance is using?

**Comment by DenverCoder1** [comment]
@Rocksheep 

       - php (8.0.11)
       - ext-imagick (3.5.1)
       - composer (2.1.8)
       - apache (2.4.49)
       - nginx (1.20.1)

I can try upgrading to the latest stack to see if it helps.

----

Haven't tried it yet, but this seems to have a possible solution:
https://legacy.imagemagick.org/discourse-server~/viewtopic6ea0.html?f=18&t=30811&start=30
> Prepend <?xml version="1.0" encoding="UTF-8" standalone="no"?> to your variable having svg text.

**Comment by Rocksheep** [comment]
Hmm strange. The versions are identical to the one I have running. We can try it with the prepended text I guess!

**Comment by DenverCoder1** [comment]
Update: It did not solve the issue

**Comment by Rocksheep** [comment]
I may have another thing that we can test. I can force Imagick to interpet the blob as an SVG. Maybe that helps?

**Comment by DenverCoder1** [comment]
Same error

```
[03-Oct-2021 18:05:33 UTC] PHP Fatal error:  Uncaught ImagickException: attempt to perform an operation not allowed by the security policy `MVG' @ error/constitute.c/IsCoderAuthorized/408 in /app/src/card.php:333
Stack trace:
#0 /app/src/card.php(333): Imagick->readImageBlob()
#1 /app/src/index.php(73): echoAsPng()
#2 {main}
   thrown in /app/src/card.php on line 333
 10.1.61.15 - - [03/Oct/2021:18:05:32 +0000] "GET /?user=DenverCoder1&type=png HTTP/1.1" 500 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
```

**Comment by Rocksheep** [comment]
This is actually a different error!

**Comment by DenverCoder1** [comment]
Indeed, you are correct.

**Comment by DenverCoder1** [comment]
It seems it's disabled for security reasons

https://devcenter.heroku.com/changelog-items/891

https://www.openwall.com/lists/oss-security/2016/05/03/18

It may be possible to override it

https://help.heroku.com/RFDJQSG3/how-can-i-override-imagemagick-settings-in-a-policy-xml-file

https://www.imagemagick.org/source/policy.xml

**Comment by DenverCoder1** [comment]
I had the `https://github.com/DuckyTeam/heroku-buildpack-imagemagick.git` buildpack added, but this was seemingly not necessary and was causing it to break.

Removing that buildpack fixed the issue.
