### ISSUE TITLE
split theme color

### ISSUE THREAD

**Issue by adityadees** [DenverCoder1/github-readme-streak-stats#15]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
Maybe if we can split this part we can get more cool color.
![xxe](https://user-images.githubusercontent.com/37553901/104156306-60cf9880-541b-11eb-9df6-66159a7768eb.png)

something like this
![xxe1](https://user-images.githubusercontent.com/37553901/104156332-6af19700-541b-11eb-8960-b1821e10fac5.png)

**Comment by DenverCoder1** [comment]
Proposed changes:

Split colors

* "stroke" becomes "border" and "stroke"
* "ring" becomes "ring" and "fire"
* "titleText" becomes "sideNums" and "sideLabels"

Name changes

* "subtitleText" becomes "dates"
* "currentStreak" becomes "currStreakNum"
* "highlight" becomes "currStreakLabel"
