### ISSUE TITLE
Ellipse behind fire shows up extra opaque when `background` is transparent

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-streak-stats#151]
**Describe the bug**
Ellipse behind fire shows up extra opaque when background is transparent

**To Reproduce**
1. Go to https://github-readme-streak-stats.herokuapp.com/demo/?user=DenverCoder1&background=%23DD2727B3
2. See color of the ellipse behind the fire icon

Or:

1. Set the parameter`background=DD2727B3` or to a similar transparent color
2. See that the background behind fire doesn't match up

**Expected behavior**
The ellipse is meant to mask out part of the ring so the background color appears behind the fire

**Screenshots**
![image](https://user-images.githubusercontent.com/20955511/135755762-927a496b-6360-44b6-9825-64bf138b254e.png)

![image](https://user-images.githubusercontent.com/20955511/135755764-f5c85fc1-6d0f-4aed-b72e-86871f174259.png)

**Desktop (please complete the following information):**
OS: Arch Linux
Browser Brave
Version 1.30.86 Chromium: 94.0.4606.61 (Official Build) (64-bit)

**Comment by komen205** [comment]
Do you have any idea how to fix this? 
So #DD2727FF is totally not transparent and #DD272700 is the most transparent.
Maybe we can compare the last two numbers and after a certain point, we set the backgruond fire color ourselves?

Any other ideas?

**Comment by DenverCoder1** [comment]
I feel like SVG should have a way to "mask out" part of a shape instead of covering it up. That would be the best solution if we can get that to work.
