### ISSUE TITLE
Composer start crashes after 5 minutes

### ISSUE THREAD

**Issue by komen205** [DenverCoder1/github-readme-streak-stats#153]
**Describe the bug**
Composer start command crashes after 300 seconds

**To Reproduce**
1. Run 'composer start'
2. Wait 300 seconds
3. Check console

**Expected behavior**
The project should run forever and it shouldn't crash after 5 minutes

**Screenshots**
![image](https://user-images.githubusercontent.com/59452877/135759191-05ab00a9-33bd-4dd9-942b-7ee5d20cfad3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 20H2

**Comment by komen205** [comment]
I think I fixed this. I can push a PR

**Comment by DenverCoder1** [comment]
Maybe it has to do with your PHP installation or other extensions you may have installed?

I've never seen this issue when using Windows or Linux.

If you can fix it without causing any new issues, then feel free to.
