### ISSUE TITLE
Refactor config.php file

### ISSUE THREAD

**Issue by komen205** [DenverCoder1/github-readme-streak-stats#154]
**Is your feature request related to a problem? Please describe.**
Instead of having a config.php file for env variables, we could have .ENV file.

**Describe the solution you'd like**
We could have a file like this, it'd be easier for new users and more simpler when the project grows.

TOKEN =
USERNAME = 

https://github.com/laravel/laravel/blob/8.x/.env.example

**Comment by komen205** [comment]
I think I can refactor this also.

**Comment by DenverCoder1** [comment]
Sounds good 👍
