### ISSUE TITLE
Warning - headers getting sent twice

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-streak-stats#162]
**Describe the bug**

```
PHP Warning:  Cannot modify header information - headers already sent by (output started at github-readme-streak-stats/src/card.php:337) in github-readme-streak-stats/src/card.php on line 303
```

This is likely caused by the following structure that appears a few places in the code.

```
if ($requestedType === "png") {
        echoAsPng($card);
    }
    echoAsSvg($card);
```

It would be best to exit the function after echoing the png.

Also since these lines appears in multiple places, it can be extracted to a function.

**Comment by komen205** [comment]
Can I do this?

**Comment by DenverCoder1** [comment]
Sure
