### ISSUE TITLE
Is this working properly?

### ISSUE THREAD

**Issue by ppmasa8** [DenverCoder1/github-readme-streak-stats#169]
**Description**

Suddenly, all the streaks disappeared.
![スクリーンショット 2021-10-04 21 47 07](https://user-images.githubusercontent.com/75968942/135854202-757b143b-5dd0-4cfb-a493-d081cedc8782.png)

![スクリーンショット 2021-10-04 21 47 28](https://user-images.githubusercontent.com/75968942/135854213-d4979351-cf42-45f4-a121-344308088cb2.png)

Is this a change due to specifications? Or is it a bug?

**Comment by DenverCoder1** [comment]
I believe it is a bug. GitHub randomly seems to not be returning any contributions, possibly due to rate-limiting. I am already looking into fixing it.

**Comment by DenverCoder1** [comment]
I can't test locally since the error only occurs on the deployed version (which makes 1000's of requests every hour).

Hopefully the last change should help. It may take a while to go into effect due to caching. If it's not fixed, I'll reopen this.
