### ISSUE TITLE
Return proper HTTP response codes for errors

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-streak-stats#171]
Currently all cards return 200 (unless there is a server error, in which case 500).

It would be best to have specific codes for different types of errors to differentiate between them.

Example:

400 - Bad request

etc.

**Comment by komen205** [comment]
If no one is going to take I can do it

**Comment by DenverCoder1** [comment]
@komen205 https://www.php.net/manual/en/function.http-response-code.php

Need to call `http_response_code()` with the code number when rendering the output. I think there may be 1 or 2 places that already have it, but it could possibly be moved to the renderOutput function.

The renderOutput function could have a default parameter for the response code and for different errors, you would pass different codes to it. If there's no error, it should just be 200 (if http_response_code is not called, the default is 200).

For example, if there's invalid data, you could call `http_response_code(422)`. Anything that does not return valid stats should have a proper error code (i.e. it won't be 200).
