### ISSUE TITLE
Add GitHub theme

### ISSUE THREAD

**Issue by Evavic44** [DenverCoder1/github-readme-streak-stats#173]
### **Describe your theme in detail**
github-commit-dark 

I honestly ran out of naming ideas. 😅 there's room for improvements If you have something better.
I just wanted a theme that matches the GitHub background and contribution graph. 
For both light and dark mode. 

### Dark
![github-commit-dark](https://user-images.githubusercontent.com/62628408/135931624-9e6bf6b8-4965-4c7d-87f6-08217ea9274f.png)

## Light

![github-commit-light](https://user-images.githubusercontent.com/62628408/135933355-4f978283-5a3e-44cc-9d12-3a711a79d287.png)

### **Color palette**
Describe the colors that could be used with this theme.

|    Property        |   Dark  |  Light  |
| ---------------  | ------------- | ------------  |
| Background:     | `#0D1117FF`  |    `#FFFFFF`   |
| Ring                 | `#39D353`      |  `#39D353`  |
| Fire                  | `#39D353`     |  `#39D353`  |
| CurrStreakNum | `#FFFFFF`     |   `#39D353` |
| CurrStreakLabel  |`#FFFFFF`     |   `#24292F` |
| Stroke                |`#39D353`   |  `#39D353` |
| Border             | `#39D353`    | `#39D353` |
| Dates        | `#1F6FEB`          | `#1F6FEB` |
| SideLabels | `#FFFFFFFF`       | `#24292F` |
| SideNums | `#FFFFFFFF`       | `#39D353` |

Are you going to add the theme?
- [x] Check for yes

**Comment by DenverCoder1** [comment]
#174 #175 Merged
