### ISSUE TITLE
Showing no contributions

### ISSUE THREAD

**Issue by AyushShahh** [DenverCoder1/github-readme-streak-stats#178]
![image](https://user-images.githubusercontent.com/71313814/136042023-d09c6eba-d2bb-4288-860c-db9ef1a6d34f.png)
It is suddenly showing this on my profile. I waited for one day hoping that it will update but it hasn't updated yet. The [link](https://github-readme-streak-stats.herokuapp.com/?user=AyushShahh&theme=highcontrast&hide_border=true) shows perfect results tho. You can check this on my [profile](https://github.com/AyushShahh)

**Comment by AyushShahh** [comment]
Okay. So anything I can do right now to display that properly?

**Comment by DenverCoder1** [comment]
> Okay. So anything I can do right now to display that properly?

If you change the URL slightly (like swap two parameters, add a `#` at the end, etc.), then GitHub will put the new version in the cache so it will show up correctly. Otherwise, just waiting should work.

**Comment by AyushShahh** [comment]
Okay thanks

**Comment by AyushShahh** [comment]
> [It's showing correctly on your profile for me](https://user-images.githubusercontent.com/20955511/136043565-70423968-4893-4bd0-952f-4cfc3f3678b0.png)
> 
> But, yeah it's a rate-limiting issue. I'm already actively trying to find a solution.

![image](https://user-images.githubusercontent.com/71313814/136050706-9c0a63ed-1f87-455f-aed2-ee93de5d6c86.png)


Yes now it showed this. I will try to change the URL slightly

**Comment by DenverCoder1** [comment]
> Yes now it showed this. I will try to change the URL slightly

Interesting, I did just change the error message to look like that, but it's strange that GitHub would update like that because they usually cache the images and I expected it to show the correct one the next time it cached.

Hopefully I can get rid of this issue soon.

**Comment by DenverCoder1** [comment]
Another thing you can do is create a Heroku account [deploy it on your own](https://github.com/DenverCoder1/github-readme-streak-stats#deploy-streak-stats-instantly).

That should avoid the rate-limit entirely since it will be coming from a different address with a different token.

**Comment by sushant-sinha** [comment]
Hi @DenverCoder1 , I tried using two different themes to just check if it's my own error... but surprisingly:

Following is the readme:

![diff](https://user-images.githubusercontent.com/60685656/136213060-08ef6389-9728-4b66-8057-ce9e50bd841c.PNG)


and my output is:

![op](https://user-images.githubusercontent.com/60685656/136213125-8df7ec70-cbb5-4864-9d97-f5227e7876f5.PNG)


Please let me know if I missed something.

PS: I love the chartreuse-dark theme ❤.

**Comment by DenverCoder1** [comment]
I've updated the requests to use GitHub's GraphQL API, so hopefully this error should no longer occur.

#185

We will find out soon.
