### ISSUE TITLE
Improve The Contribution Guidelines Documentation

### ISSUE THREAD

**Issue by shubhamjha25** [DenverCoder1/github-readme-streak-stats#183]
The **`CONTRIBUTING.md`** file doesn't mentions the steps how to contribute (Clone, Fork, Create a Branch etc etc).
It mentions the project's local installation and setup but doesn't mentions the instructions of how to contribute. 

I wish to add a detailed workflow of the steps to contribute.
It will help the beginners, reduce the chances of errors, enhance the documentation and help to manage the open-source project more efficiently.

**Comment by DenverCoder1** [comment]
That sounds great!

https://github.com/denvercoder1/readme-typing-svg has almost the same info in the file, so feel free to contribute there as well.
