### ISSUE TITLE
Streak doesn't match the contributions

### ISSUE THREAD

**Issue by arndom** [DenverCoder1/github-readme-streak-stats#189]
**Description**

Yesterday my streak was in the 90s but it says 3 today. I find it very strange.

**To Reproduce**

Go to my profile and take a look the two don't match:

![image](https://user-images.githubusercontent.com/40564798/136659068-65260537-764d-4448-9edc-fa18134be858.png)

![image](https://user-images.githubusercontent.com/40564798/136659080-c991f721-0cb4-4858-8fc3-fc24d35d8eaf.png)

**Comment by arndom** [comment]
That's strange, private contributions are turned on
![image](https://user-images.githubusercontent.com/40564798/136674946-0bf0ee14-f6d3-471a-bec4-23982e91d9fa.png)

**Comment by arndom** [comment]
Also, checked using incognito and got this:
![image](https://user-images.githubusercontent.com/40564798/136675265-f24d42a8-bab6-4ed8-8734-f727ffb7b834.png)

**Comment by DenverCoder1** [comment]
It could be a timezone issue. For me it shows 2 contributions on October 7 and none on October 6, whereas for yours it looks like 1 on each.

![image](https://user-images.githubusercontent.com/20955511/136693712-5521e9c1-a243-49f6-8037-3fbab14303d0.png)

I will look into it.

**Comment by arndom** [comment]
Yeah, it's 1 on each. Alright, good luck 👍

**Comment by arndom** [comment]
Yh I tried and it's still the same.

**Comment by arndom** [comment]
Well, the streak still isn't accurate but it's manageable

**Comment by arndom** [comment]
Well, closing it is alright I guess,  earlier today it showed the correct value but it's reverted back 🤷‍♂️.
