### ISSUE TITLE
Displays wrong stats after crossing 100 days 

### ISSUE THREAD

**Issue by devmohit-live** [DenverCoder1/github-readme-streak-stats#194]
**Describe the bug**
Displays wrong stats after crossing 100 days , its actually 150+ days of streak but from last few days  days it is showing 86 and sometimes 77.
Sometimes it shows the correct streak , sometimes not.

**Comment by Priyansh-Kedia** [comment]
Same issue with me
I am facing the issue for less than 10 days too.

My streak was reset to 0 from around 39, and now again has been reset to 1

**Comment by DenverCoder1** [comment]
Do you have private contributions that aren't set to be displayed?

@Priyansh-Kedia This is what I see when viewing your profile
![image](https://user-images.githubusercontent.com/20955511/150389946-c93b5d3a-0230-41de-adb1-e63dc1aa1db4.png)

The data displayed on the card is exactly how it is received from the GitHub API.

**Comment by ccarver80** [comment]
I had a weird one, I got home late one night (9:30pmMST) checked my GitHub and it showed I lost my streak so I figured GitHub's servers were on a different time zone no big deal, but I pushed something anyway and my streak came back :shrug:

**Comment by koushalkishor** [comment]
I lost my streak one day suddenly it shows my streak 0 from 11 and it is not showing my contribution properly even after i pushed commits on github  if i pushing around 10 or more commits its hardly showing 1 and next day again it showing my streak 0

**Comment by Nasim-Mahmud** [comment]
After completing 34 days, it's suddenly showing 0 streaks instead of 35! :/

**Comment by DenverCoder1** [comment]
I have a theory the timezone used by the cards is based on the timezone of the user who provided the token.

You could try self hosting it if you'd like to see if the stats match your chart better.

https://github.com/DenverCoder1/github-readme-streak-stats#-deploying-it-on-your-own

If you do try it, let me know if you think that works.

Closing as there is no alternate solutions known as of now.
