### ISSUE TITLE
Weekly contribution mode

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-streak-stats#196]
**Is your feature request related to a problem? Please describe.**

Contributing to GitHub every day is a huge commitment.

Some users may want the option to take off on the weekends or at other busy times during their week due to other life commitments.

Having only the option to show a daily streak makes it so that people who can't contribute every day won't have a  streak to show off.

**Describe the solution you'd like**

Add a "Week Streak" mode, toggle-able from the url options that will display the number of consecutive weeks instead of days.

This will allow more users to have a streak they are proud to display.

**Comment by 7PH** [comment]
Hi all, thank you for this awesome project, I am wondering whether anyone has planned to work on this in the next 3-6 months?

**Comment by DenverCoder1** [comment]
There's no one assigned, if you'd like to contribute, feel free to make a pull request. It also probably wouldn't take me very long if you'd prefer I do it.

**Comment by 7PH** [comment]
Thank you for your answer @DenverCoder1 
My first post sounded a bit too specific, as I was really asking out of curiosity - please do not feel any pressure to work on this, although I will keep on watching this project 👍

**Comment by DenverCoder1** [comment]
Feel free to try it out and let me know what you think.

`&mode=weekly`
