### ISSUE TITLE
[Question] How does it count streak ?

### ISSUE THREAD

**Issue by Arsenic-ATG** [DenverCoder1/github-readme-streak-stats#2]
Does it mean how many continuous days I log-in to my account or how many days I have contributed continuously to GitHub ?

**Comment by DenverCoder1** [comment]
@Arsenic-ATG  The contributions graph shows the number of consecutive days you have made a contribution. Contributions are counted in the same way they are in the contributions graph (i.e. a commit, pull request, or issue in a standalone repository).

[This page explains how GitHub counts contributions] (https://docs.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile)
