### ISSUE TITLE
UNCONDITIONALLY MY STREAK IS BROKEN 

### ISSUE THREAD

**Issue by Moinuddin9777** [DenverCoder1/github-readme-streak-stats#203]
I never broke the streak for 22 days please have a look at my contributions chart 
But out of the blue, I get to see this...!!!
Please tell me a way to get my streak score back 

![image](https://user-images.githubusercontent.com/76849575/149890115-2bb4346c-0fab-4253-8110-e49e92dc91d0.png)
![image](https://user-images.githubusercontent.com/76849575/149890708-7c60a52d-3987-4fa9-a077-e2916c799df1.png)
![image](https://user-images.githubusercontent.com/76849575/149890761-0080ca92-1664-46fd-8528-0ff31dff6070.png)

**Comment by DenverCoder1** [comment]
Your contribution graph looks different to me

![image](https://user-images.githubusercontent.com/20955511/150057205-36408f51-4057-4510-a30b-abe3097c2d12.png)

Maybe you have private contributions, or it's possible that the contributions are displayed for you for a different timezone?

I don't know what causes this issue, but the data displayed is the exact same as the data I get from the GitHub API so there isn't much I can do about it.

**Comment by Moinuddin9777** [comment]
YES! you're right turned on private contributions and I got my streak back...!!!
Thank you
YOU'RE AWESOME!
