### ISSUE TITLE
Add Transparent theme

### ISSUE THREAD

**Issue by mqliang** [DenverCoder1/github-readme-streak-stats#206]
**Is your feature request related to a problem? Please describe.**

With the introduction of dark mode in Github it has become difficult to set an image background that looks consistent with the background in both dark and light mode.

To solve this the most obvious solution was to make the background transparent. All that was left was to choose colors for text that makes it legible in light as well as dark background.

Is it possible to add a "Transparent theme" so that it looks good on both light and dark Github mode?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mqliang** [comment]
FYI. Here is a PR add a Transparent theme to [github-readme-stats
](https://github.com/anuraghazra/github-readme-stats) project: https://github.com/anuraghazra/github-readme-stats/pull/1010

**Comment by DenverCoder1** [comment]
There are a few transparent themes already added such as

gruvbox_duo, tokyonight_duo, onedark_duo, blueberry_duo

**Comment by DenverCoder1** [comment]
Revisiting this as an issue to add the "transparent" theme from [github-readme-stats](https://github.com/anuraghazra/github-readme-stats) to this project to allow for easier theme consistency.
