### ISSUE TITLE
Logo Enhancement

### ISSUE THREAD

**Issue by DalpatRathore** [DenverCoder1/github-readme-streak-stats#210]
Hey! @DenverCoder1 
 &nbsp;&nbsp;&nbsp; I have tinkered  around **github-readme-streak-stats** logo to give 3D style. Please have a look. 
Logo dimension - 130 x 145
- ProtoType - 1

 | GitHub Light Theme | GitHub Dark Theme |
 | -------------- | --------------  |
 | <img width="500" alt="logo-proto-1-white-bg" src="https://user-images.githubusercontent.com/69510006/151662076-14d4a09f-2b68-4e1b-aea9-20f58b9885f3.png">    |  <img width="500" alt="logo-proto-1-black-bg" src="https://user-images.githubusercontent.com/69510006/151662082-8f0a8756-072f-47fe-ae01-bc68d50ceec3.png">   |

- ProtoType - 2

| GitHub Light Theme | GitHub Dark Theme |
| ----------- | ----------- |
| <img width="500" alt="logo-proto-2-white-bg" src="https://user-images.githubusercontent.com/69510006/151662084-4f60e08f-c09d-40b3-b658-4cd0f4c153a2.png"> | <img width="500" alt="logo-proto-2-black-bg" src="https://user-images.githubusercontent.com/69510006/151662089-10f64b26-eeb6-4ba6-92d7-29b5daf022fc.png">       |

Thanks

**Comment by DenverCoder1** [comment]
Sorry for not responding to this in a timely manner.

Thanks for suggesting the logos. They are nice, but I personally feel that the flat design that the repo currently has is good the way it is and the shadow/bevel effect is not necessary.

I'll close this issue, but feel free to contribute and share your thoughts or other ideas in the future. :rocket:
