### ISSUE TITLE
Add Discussions in calculations as new contribution

### ISSUE THREAD

**Issue by shaggy-axel** [DenverCoder1/github-readme-streak-stats#213]
New feature `discussions` in github repo taken into account when counting contributions

Example:
I have 1040 contributions and 2 contributions as started discussions
![image](https://user-images.githubusercontent.com/79697348/151795909-231dbe87-0fcc-4744-8cbb-b58dd1e3253d.png)
![image](https://user-images.githubusercontent.com/79697348/151795923-69291ca8-1198-4add-97b3-458d02651d2b.png)
![image](https://user-images.githubusercontent.com/79697348/151795934-4b3260fb-7379-4349-bdd8-3b858170cdd0.png)

**Comment by DenverCoder1** [comment]
Anything GitHub counts on the graph is included.

Maybe you have private contributions that are not being  displayed. There is a toggle next to the contribution graph for that

**Comment by shaggy-axel** [comment]
> Anything GitHub counts on the graph is included.
> 
> Maybe you have private contributions that are not being displayed. There is a toggle next to the contribution graph for that

No, I got this, but an hour later
