### ISSUE TITLE
Wrong Date (in Day) being displayed

### ISSUE THREAD

**Issue by agentmishra** [DenverCoder1/github-readme-streak-stats#223]
**Describe the bug**
**A clear and concise description of what the bug is.**

I just noticed that, after 12:01am activity, the github contribution box becomes green, but the stats day do not match up with it, say up till 3-4am of activity
any activity after that is in sync

just to mention, i am based in India, may be its a time zone issue with the app host

will be awesome if its fixed!

**Comment by DenverCoder1** [comment]
I have a theory the timezone used by the cards is based on the timezone of the user who provided the token.

You could try self hosting it if you'd like to see if the stats match your chart better.

https://github.com/DenverCoder1/github-readme-streak-stats#-deploying-it-on-your-own

If you do try it, let me know if you think that works.

Closing as there is no alternate solutions known as of now.

**Comment by agentmishra** [comment]
ok i will try and update the same
