### ISSUE TITLE
Counting non default branches

### ISSUE THREAD

**Issue by CuzImBisonratte** [DenverCoder1/github-readme-streak-stats#225]
**Is your feature request related to a problem? Please describe.**
I'm Frustrated, that when i contribute to any branch thats not the default branch, it doesn't count, even though im Contributing.

**Describe the solution you'd like**
Also contributions that aren't on the default branch of a repository will be counted.

**Comment by DenverCoder1** [comment]
The Github API only displays commits made on the default branch or `gh-pages` branch.

There are many things that I find annoying about GitHub's contributions API but there isn't really much I can do about it

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile
