### ISSUE TITLE
Update docs to require PHP v8.1+

### ISSUE THREAD

**Issue by donutboy929** [DenverCoder1/github-readme-streak-stats#255]
`IntlDatePatternGenerator` is a new class in PHP 8.1 so the required version of PHP should be updated in the docs from 8.0+ to 8.1+.

**Describe the bug**
The following error is thrown when running the project using PHP version 8.0.20.
`Uncaught Error: Class "IntlDatePatternGenerator" not found in C:\<path-to-repo>\github-readme-streak-stats\src\card.php:17`

When running the demo, the preview image does not render.

**Screenshots**
![image](https://user-images.githubusercontent.com/47971350/173243584-fa1157a3-f7a0-4a86-8cfa-2e3796d71c29.png)

**Comment by DenverCoder1** [comment]
Thanks for noticing this :+1:
