### ISSUE TITLE
no-background feature

### ISSUE THREAD

**Issue by ronhuidrom** [DenverCoder1/github-readme-streak-stats#267]
**Is your feature request related to a problem? Please describe.**
I want a transparent background feature. None of the themes are such that when I toggle between light and dark mode, the background remains transparent.

**Describe the solution you'd like**
When used in light mode, only the text should be visible with no background. The same should happen in dark mode. So, whether it's in light mode or dark mode, the background remains transparent. 

**Describe alternatives you've considered**
Have tried various themes. None suits my liking.

**Comment by DenverCoder1** [comment]
There are a few transparent themes already added such as

gruvbox_duo, tokyonight_duo, onedark_duo, blueberry_duo

You can use the color `0000` or `00000000` for a transparent background. The alpha value set to 0 will make it transparent.
