### ISSUE TITLE
Add animations to the SVGs

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-streak-stats#27]
Currently, the graphics appear suddenly as they are loaded. There is no fade-in animation or motion.

It may be cool to have some sort of CSS animation as the image loads on the page (similar to how it is done with [GitHub Readme Stats](https://github.com/anuraghazra/github-readme-stats). See this [example](https://github-readme-stats.vercel.app/api?username=DenverCoder1).)

**Comment by PhoenixCreation** [comment]
#30 Check out.
