### ISSUE TITLE
Streak reset to 0 even though I did stuff today

### ISSUE THREAD

**Issue by ItsHypers** [DenverCoder1/github-readme-streak-stats#275]
**Describe the bug**
My Streak reset to 0, even though I worked on something today

**To Reproduce**
I'm not sure. I just worked on a project as usual and noticed my streak went to 0 even though I worked on stuff.

**Expected behavior**
For the streak to continue from where it was.

**Screenshots**
![image](https://user-images.githubusercontent.com/59265736/178165525-bc3b9183-c5a1-434c-a78c-0c9fb407f45d.png)
![image](https://user-images.githubusercontent.com/59265736/178165527-941cbf8a-fe43-43d7-8921-2278fabcaf91.png)

**Desktop (please complete the following information):**

- Windows 11
- Chrome

**Comment by DenverCoder1** [comment]
There are a couple possibilities I can think of:

1. You made private contributions and you have the setting for displaying them turned off. (You can use the Contribution Settings pulldown next to the graph to change this)
2. GitHub is displaying the graph for you in a different timezone.

The stats used by the card are directly taken from the GitHub API.

When I view your profile, I am also seeing no contributions on July 9.

![image](https://user-images.githubusercontent.com/20955511/178909132-aa2486de-0961-437a-8598-319863190459.png)

**Comment by DenverCoder1** [comment]
I have a theory the timezone used by the cards is based on the timezone of the user who provided the token.

You could try self hosting it if you'd like to see if the stats match your chart better.

https://github.com/DenverCoder1/github-readme-streak-stats#-deploying-it-on-your-own

If you do try it, let me know if you think that works.

Closing as there is no alternate solutions known as of now.
