### ISSUE TITLE
Github readme streak stats resetting despite having an ongoing streak

### ISSUE THREAD

**Issue by prathikshetty2002** [DenverCoder1/github-readme-streak-stats#276]
**Issue faced**
I have been consistently working on github from last 15 days my current streak was 13 till 2 days ago. Now it is only 2 but i didn;t break it. The readme stats is not showing the streak record properly. 

**Expected behaviour**
The current streak should be of 15 days but is instead of 2 days

![Screenshot 2022-07-19 010816](https://user-images.githubusercontent.com/63772910/179603568-b8b12278-4f18-44f2-9884-84cbbc5b8243.png)

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

![Screenshot 2022-07-19 005827](https://user-images.githubusercontent.com/63772910/179602695-9c533f5f-cd66-48cb-bc88-381bf8b84e82.png)

I have private contributions enabled and also have read the existing contribution guidelines of readme stats card.

**Comment by DenverCoder1** [comment]
The stats are taken directly from the Github API so there isn't anything I can think of that can fix this.

Also, when I view your profile, I don't see any contributions from 4 days ago.

It might be a timezone issue

![Screenshot_20220719-013825](https://user-images.githubusercontent.com/20955511/179694203-61cb5f74-4115-4e5f-b200-6e25f23819f9.png)

**Comment by prathikshetty2002** [comment]
> The stats are taken directly from the Github API so there isn't anything I can think of that can fix this.
> 
> Also, when I view your profile, I don't see any contributions from 4 days ago.
> 
> It might be a timezone issue
> 
> ![Screenshot_20220719-013825](https://user-images.githubusercontent.com/20955511/179694203-61cb5f74-4115-4e5f-b200-6e25f23819f9.png)

Oh i can see the graph on my side displays the contributions properly. Thanks i will look into it <3 .

**Comment by DenverCoder1** [comment]
It's possible if you were to self-host it and use a GitHub token for your own account, it might display in your timezone. I have not tested this theory yet, so if you'd like to try it and let me know the results, that would be helpful.

**Comment by prathikshetty2002** [comment]
@DenverCoder1 that's a good idea to check the effects of timezone , i will try it and tell the difference👍
