### ISSUE TITLE
GitHub Streak Stats 

### ISSUE THREAD

**Issue by adityasgit-hub** [DenverCoder1/github-readme-streak-stats#281]
**GitHub Streak Stats not working properly!**

So since the day I joined GitHub, I am continuously contributing to it and so I thought of adding a streak stats as it will motivate me to keep going but it has gone completely wrong as it is showing that my streak is 4 (: I need help!

**Comment by adityasgit-hub** [comment]
If I convert my private repos. to public repos. will my streak stats get changed?

**Comment by DenverCoder1** [comment]
It appears to be showing correctly now, timezone differences and caching could affect it.

![image](https://user-images.githubusercontent.com/20955511/180479651-7e8373cb-7b1f-4882-99bc-cc150060a89f.png)

If you want private repos to count, you can enable the setting on the contribution graph

![image](https://user-images.githubusercontent.com/20955511/180479984-b69dad0c-1ad4-47d6-ae4d-90b533238dd6.png)

**Comment by adityasgit-hub** [comment]
Thanks a lot! Denver, appreciate it!
