### ISSUE TITLE
Streak is reset when it shouldn't

### ISSUE THREAD

**Issue by Wjplatformer** [DenverCoder1/github-readme-streak-stats#289]
**Describe the bug**
Although I currently have a 10 commit streak, the Stats reset to 1 for my current streak. 

**To Reproduce**
1. Go to https://github.com/Wjplatformer
2. View the main streak and my Contribution graph

None

**Expected behavior**
Have 10 commit streak show up on current streak.

**Screenshots**
![image](https://user-images.githubusercontent.com/82447031/181903709-b605d026-1d72-4faa-821e-7625faef7a1e.png)
![image](https://user-images.githubusercontent.com/82447031/181903738-8cb76d71-629e-4161-8cdf-ca94ffd8f3c8.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Home
- Browser: Chrome
- Version 103.0.5060.134 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
None

**Comment by DenverCoder1** [comment]
There is nothing that can be done about this. According to the GitHub API, you have no contributions on July 28 and the stats are displayed exactly how they are received from the API.

Contribution dates are timezone-dependent, so it is possible for your browser to show it differently than the official API.

You can possibly try self-hosting with your own personal access token to see if it accounts for the timezone difference.

I will close this for now as nothing I can do about this unless GitHub makes changes to their API.

**Comment by Wjplatformer** [comment]
Thanks.

**Comment by Wjplatformer** [comment]
Thanks :)
