### ISSUE TITLE
wrong year

### ISSUE THREAD

**Issue by nschloe** [DenverCoder1/github-readme-streak-stats#291]
http://github-readme-streak-stats.herokuapp.com?user=nschloe&theme=dracula&hide_border=true

![screenshot](https://user-images.githubusercontent.com/181628/183069035-6ce7d95c-53c3-4928-b163-eb96c307fa07.png)

**Comment by DenverCoder1** [comment]
Thanks for reporting, apparently in the PHP Intl lib `YYYY` is the year of the "week of year" which can be different in the last week of year (ending in January of the following year). V
