### ISSUE TITLE
Add &border_radius param

### ISSUE THREAD

**Issue by mpotane** [DenverCoder1/github-readme-streak-stats#320]
add border-radius in card that can be set like 15px.

**Comment by nishith-p-shetty** [comment]
Replace line no. 182 in card.php 
from > <rect width='495' height='195'/>
with  > <rect width='495' height='195' rx='15'/>

**Comment by DenverCoder1** [comment]
> Replace line no. 182 in card.php 
> from > `<rect width='495' height='195'/>`
> with  > `<rect width='495' height='195' rx='15'/>`

That looks good for the roundness, I think it makes the border color less visible though.

I might recommend instead changing the place that it currently has rounding, but make it customizable and do some shifting to make sure the border color is visible, in other words, changing the path on 191-192 to a rounded rectangle like this:

```diff
- <path d='M 4.5 0 L 490.5 0 C 492.984 0 495 2.016 495 4.5 L 495 190.5 C 495 192.984 492.984 195 490.5 195 L 4.5 195 C 2.016 195 0 192.984 0 190.5 L 0 4.5 C 0 2.016 2.016 0 4.5 0 Z'
-       style='stroke: {$theme["border"]}; fill: {$theme["background"]};stroke-miterlimit:10;rx: 4.5;'/>

+ <rect style='stroke: {$theme["border"]}; fill: {$theme["background"]}; x: 0.5px; y: 0.5px; rx: {$borderRadius}; width: calc(100% - 1px); height: calc(100% - 1px);'/>
```

As far as reading the parameter, you can see examples in the `generateCard` function, similar to how it is done for locale, date_format, etc. Here's an example of one way to do it:

```php
// read border_radius parameter, default to 4.5 if not set
$borderRadius = $params["border_radius"] ?? "4.5";
```

You can also do the same in the `generateErrorCard` function.

It would also be nice if you could update the demo site with the new field and add unit tests. Feel free to let me know if you have any questions or need help with anything.

**Comment by nishith-p-shetty** [comment]
What if he uses dark theme >>> https://nps-github-readme-streak-stats.herokuapp.com/?user=DenverCoder1&theme=blue-green&hide_border=true

**Comment by nishith-p-shetty** [comment]
> > Replace line no. 182 in card.php
> > from > `<rect width='495' height='195'/>`
> > with  > `<rect width='495' height='195' rx='15'/>`
> 
> That looks good for the roundness, I think it makes the border color less visible though.
> 
> I might recommend instead changing the place that it currently has rounding, but make it customizable and do some shifting to make sure the border color is visible, in other words, changing the path on 191-192 to a rounded rectangle like this:
> 
> ```diff
> - <path d='M 4.5 0 L 490.5 0 C 492.984 0 495 2.016 495 4.5 L 495 190.5 C 495 192.984 492.984 195 490.5 195 L 4.5 195 C 2.016 195 0 192.984 0 190.5 L 0 4.5 C 0 2.016 2.016 0 4.5 0 Z'
> -       style='stroke: {$theme["border"]}; fill: {$theme["background"]};stroke-miterlimit:10;rx: 4.5;'/>
> 
> + <rect style='stroke: {$theme["border"]}; fill: {$theme["background"]}; x: 0.5px; y: 0.5px; rx: {$borderRadius}; width: calc(100% - 1px); height: calc(100% - 1px);'/>
> ```
> 
> As far as reading the parameter, you can see examples in the `generateCard` function, similar to how it is done for locale, date_format, etc. Here's an example of one way to do it:
> 
> ```
> // read border_radius parameter, default to 4.5 if not set
> $borderRadius = $params["border_radius"] ?? "4.5";
> ```
> 
> You can also do the same in the `generateErrorCard` function.
> 
> It would also be nice if you could update the demo site with the new field and add unit tests. Feel free to let me know if you have any questions or need help with anything.

I am asking where is the paat of code where u r taking parameters from link and storing it

```
// read border_radius parameter, default to 4.5 if not set
$borderRadius = $params["border_radius"] ?? "4.5";
```

👆tried this but got error on line 15 at column 48: error parsing attribute name

**Comment by nishith-p-shetty** [comment]
You can check out border radius here >>>> https://nps-github-readme-streak-stats.herokuapp.com/?user=DenverCoder1&theme=blue-green&hide_border=true&border_radius=20

Demo site >>> https://nps-github-readme-streak-stats.herokuapp.com/demo

**Comment by DenverCoder1** [comment]
> You can check out border radius here >>>> https://nps-github-readme-streak-stats.herokuapp.com/?user=DenverCoder1&theme=blue-green&hide_border=true&border_radius=20
> 
> Demo site >>> https://nps-github-readme-streak-stats.herokuapp.com/demo

Looks good, but as I mentioned earlier it should be changed in the other place instead (191-192)  because that's where the border stroke is applied.

https://nps-github-readme-streak-stats.herokuapp.com/?user=DenverCoder1&theme=blue-green&border_radius=20&border=f00

![Screenshot_20220911-001635.png](https://user-images.githubusercontent.com/20955511/189515062-31162a81-f5fe-47be-82d6-7c0f5ec93314.png)

This is what it does if you apply it to the clipPath instead of the actual rectangle.

The suggestion I put earlier makes it so the border is more visible and works with border radius 0 since it replaces the old rounding effect.

**Comment by nishith-p-shetty** [comment]
FIXED try now...

You can check out border radius here >>>> https://nps-github-readme-streak-stats.herokuapp.com/?user=DenverCoder1&theme=blue-green&hide_border=true&border_radius=200

Demo site >>> https://nps-github-readme-streak-stats.herokuapp.com/demo
