### ISSUE TITLE
Streaks are only counted from January 1st

### ISSUE THREAD

**Issue by KentoNishi** [DenverCoder1/github-readme-streak-stats#328]
**Describe the bug**
Streaks seem to only be counted from January 1st, 2022. This started happening in the past few days.

**To Reproduce**

1. Go to https://github.com/KentoNishi
2. Observe that the streak is at around 275 days despite my commit graph clearly showing a multi-year streak. The count begins on Jan. 1st, 2022,

**Expected behavior**
The streak should account for all of time.

**Screenshots**
<img width="687" alt="image" src="https://user-images.githubusercontent.com/38841491/193437990-4f4d5006-ae3e-4fa8-a6aa-cd56ca08201b.png">

My 1000-day streak: https://twitter.com/kento_nishi/status/1552042067198504960

**Comment by anish-lakkapragada** [comment]
I also have this exact same issue as well. 

My streak reached one year 1-3 days ago, and unfortunately it had to be counted as only to the beginning of the year shortly after. 

**Proof Of Past Streak**

![image](https://user-images.githubusercontent.com/68448458/193438066-2e2c0558-c7eb-4984-91ad-022c8634b899.png)

Also Heroku no longer for free, so maybe deploy to [Deta](https://www.deta.sh/).

**Comment by SamuelMarks** [comment]
Ditto, I have over 700 days in a row, but now it says:
<img width="503" alt="Screen Shot 2022-10-01 at 11 43 44 PM" src="https://user-images.githubusercontent.com/807580/193438251-d6e8694c-d390-497e-b5ff-37e70a717aed.png">

…or dynamically:
![SamuelMarks](https://github-readme-streak-stats.herokuapp.com/?user=SamuelMarks)

Would be great to have this fixed. Thanks

**Comment by tommyettinger** [comment]
This seems to be Heroku-related; when I changed the domain from `github-readme-streak-stats.herokuapp.com` to `streak-stats.demolab.com`, my full 8+ year streak was back and shown normally.

**Comment by DenverCoder1** [comment]
> This seems to be Heroku-related; when I changed the domain from `github-readme-streak-stats.herokuapp.com` to `streak-stats.demolab.com`, my full 8+ year streak was back and shown normally.

Both are running the same code on Heroku currently. The demolab subdomain is just a custom domain added to the project currently. So that's unlikely the issue, probably due to caching.

**Comment by DenverCoder1** [comment]
Nothing changed in the code in the past few days. My best guess is that it's an issue with the GitHub API being inconsistent as usual.

**Comment by SamuelMarks** [comment]
Thanks. Yeah as you can see by my comment the dynamic one has fixed itself. Great!
