### ISSUE TITLE
Contributions are now showing only from Jan 1

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [DenverCoder1/github-readme-streak-stats#342]
Old
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/83284294/197337953-fee7c618-4b64-4ca0-aaa3-66557364859f.png">

New (bug)

<img width="503" alt="image" src="https://user-images.githubusercontent.com/83284294/197337939-a583784b-028b-4a68-9307-6e51f685e90d.png">

**Comment by Nirzak** [comment]
Same here

**Comment by 1995parham** [comment]
Same here

**Comment by HamiltonMultimedia** [comment]
Mine shows from May 10th suddenly. 
My contributions date back to 2017.
I thought I was trippin. 

![Screen Shot 2022-10-22 at 8 19 10 PM](https://user-images.githubusercontent.com/24661651/197367319-ba288f6a-9a28-4128-873a-b1a9654b4f0c.png)

**Comment by DenverCoder1** [comment]
I'm seeing the issue as well, but unfortunately I can't reproduce the issue locally.

When running on localhost everything appears correct.

![image](https://user-images.githubusercontent.com/20955511/197369686-efcc9085-48d6-4e46-96ab-fb7f5dc908ea.png)

Nothing has changed recently in the code, so it probably has to do with the GitHub API being inconsistent, as it frequently is.

**Comment by DenverCoder1** [comment]
Seems like the issue resolved itself as I expected it would.

> ![image](https://user-images.githubusercontent.com/20955511/197370604-cb3d4057-c373-4362-abba-69ae176a1c5e.png)

I can only make it as accurate as the GitHub API allows.
