### ISSUE TITLE
Github Steak

### ISSUE THREAD

**Issue by Kumilachew-g** [DenverCoder1/github-readme-streak-stats#344]
**Streak problem on my side**

It was working but today it forgot the count and start from 1. What is the issue?

**Comment by DenverCoder1** [comment]
It looks like it's on 30 when I view it.

The issue is not with Streak Stats since it is just getting the information from GitHub's API which occasionally is inconsistent and breaks.

**Comment by Kumilachew-g** [comment]
Thanks, man!!!
I push my commits from my local. Notify it in my repo. But not in my contribution graph. What will be the issue?
Thanks again!!

**Comment by DenverCoder1** [comment]
> I push my commits from my local. Notify it in my repo. But not in my contribution graph. What will be the issue? Thanks again!!

You can see here how they are counted - https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile

It needs to be on the main or default branch of the repo, not in a fork. Also if it's a private repo, you need to enable to setting from the dropdown near the chart.
