### ISSUE TITLE
GitHub README Streak Stats Displaying 0 Values 

### ISSUE THREAD

**Issue by jesterb0206** [DenverCoder1/github-readme-streak-stats#349]
**Describe the bug**

On my profile README it's displaying none of my stats, all of the values are 0. However, if I change the username from mine to someone else's it displays correct stats. 

**To Reproduce**

1. Go to 'https://github.com/jesterb0206/jesterb0206'
2. Scroll down to my GitHub README streak stats
3. See error

**Expected behavior**

As of writing this I should have 138 contributions, and I don't know off the top of my head what my longest streak is (I think 4 or 5) but I've made contributions today and yesterday so my current streak should be 2. 

**Screenshots**

<img width="1792" alt="Screen Shot 2022-11-08 at 12 04 45 AM" src="https://user-images.githubusercontent.com/109996512/200511052-1bcc1270-4b50-4203-af73-d1c4fe95a557.png">

<img width="1792" alt="Screen Shot 2022-11-08 at 12 09 23 AM" src="https://user-images.githubusercontent.com/109996512/200510942-4a90bb79-b5b1-4e3e-9196-0fec8255dd8f.png">

**Desktop (please complete the following information):**

- OS: macOS Monterey Version 12.1
- Browser Safari
- Version 15.2

**Smartphone (please complete the following information):**

- Device: iPhone 12 
- OS: Software Version 15.6.1
- Browser Safari
- Version Unsure (maybe 15.2 as well, couldn't tell you)

**Additional context**

I see that for my GitHub stats the only correct value is the total stars that I've earned, the rest of the values are displaying 0 as well which is incorrect. Interestingly, my most used languages is correct. I'm wondering if this is an issue with GitHub and not GitHub README Streak Stats.

**Comment by DenverCoder1** [comment]
![Screenshot_20221108-025703](https://user-images.githubusercontent.com/20955511/200534027-baf37efa-f9a4-4fca-bbb5-bd77eb46709f.png)

You must have told GitHub to make your activity private.

Your options are to either make your activity public or self-host the projects with a repo-scope personal access token.
