### ISSUE TITLE
Submarine Flowers (New Theme Idea)

### ISSUE THREAD

**Issue by jesterb0206** [DenverCoder1/github-readme-streak-stats#350]
**Describe your theme in detail**

Hi Jonah or anyone who is reading this, I have a theme that I would like someone else to add (I would try adding it myself but I don't have PHP installed and I'm scared to mess around with it myself for the first time ever). I don't know if it matters but I think my Border Radius is 10 in the image below. I was hoping to call it **Submarine Flowers** after a song lyric from a song I listened to a lot as a child. 

**Include a screenshot / image**

<img width="550" alt="Screen Shot 2022-11-11 at 4 15 34 PM" src="https://user-images.githubusercontent.com/109996512/201446740-447f026b-bbd9-47fe-b3eb-51e80b40aa55.png">

**Color palette**

Background: **#013E4E**
Border: **#013E4E**
Stroke: **#48FF50**
Ring: **#FF8888**
Fire: **#FF8888**
CurrStreakNum: **#FFF000**
SideNums: **#FFF000**
CurrStreakLabel: **#FFF000**
SideLabels: **#FF8888**
Dates: **#FF8650**

Are you going to add the theme?

- [ ] Check for yes

**Comment by DenverCoder1** [comment]
Looks great!

Are you sure you don't want to try contributing it yourself?

I think it should be possible to contribute a theme without knowing or running PHP. All that needs to be done is updating the [themes.php](https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/src/themes.php) and themes documentation.

The themes.php is just a mapping of colors (the advanced mode on the demo site also has a button to export to PHP to get it all formatted correctly to add to the end of the file).

As long as you can keep the formatting consistent, it shouldn't be a problem. I can also test and help out with the formatting or preview image steps after you open a PR.

So let me know what you decide. 👍

I'd be happy to have you contribute, but if you decide you'd rather not, that's also totally fine.

**Comment by jesterb0206** [comment]
Hi Jonah,

Thank you for encouraging me to try contributing it myself! I have a group project for my coding bootcamp that begins next week and it was good practice creating a new branch, opening up a pull request, etc. I opened a new pull request (#351) with my changes to `themes.php` and `docs/themes.md`. It just needs approval and then it should be good to go! 

Bradley
