### ISSUE TITLE
 Different images for dark mode and light mode CSS styling

### ISSUE THREAD

**Issue by rafael-c-alexandre** [DenverCoder1/github-readme-streak-stats#354]
**Describe the bug**
When using the recommended `prefers-color-scheme: dark` to use different images for light/dark mode on Firefox with v. 107.0 (64-bit), I get images that appear to be missing its CSS styling. I only observed this behaviour when using Firefox on my Mac. Everything was fine on Chrome, Safari and Firefox (iPhone).

**To Reproduce**

1. Open Firefox as your web browser.
2. Use the recommended way to achieve different dark/light mode images described [here](https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/faq.md#how-do-i-make-different-images-for-dark-mode-and-light-mode). In my case, it was:
```
<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://streak-stats.demolab.com?user=rafael-c-alexandre&theme=dark&border_radius=3" />
    <img src="https://streak-stats.demolab.com?user=rafael-c-alexandre&border_radius=3" alt="streak stats" />
  </picture>
```
3. Preview image with dark or light mode.
4. See error.

**Expected behavior**

Images with the correct styling like shown below. (In this case, I use the default theme and the dark one)

![light](https://user-images.githubusercontent.com/44480935/203587556-91d2563a-927b-4af7-b4cd-f1cd552fc794.png) ![dark](https://user-images.githubusercontent.com/44480935/203587956-84ac8f16-70b3-40b0-ba0f-c0b63d8a515f.png)

**Screenshots**

Instead of what is presented above, I got the following images: 

<img width="496" alt="light-corrputed" src="https://user-images.githubusercontent.com/44480935/203588272-8da6c877-03ad-4b37-a317-9104034c2b44.png">
<img width="495" alt="dark-corrupted" src="https://user-images.githubusercontent.com/44480935/203588436-8ab69369-1fc0-46c4-8112-d362d807def0.png">

**Desktop (please complete the following information):**

- OS: macOS Ventura
- Browser: Firefox
- Version: 107.0 (64-bit)

**Smartphone (please complete the following information):**
Not applicable

**Additional context**
Not applicable

Thank you guys in advance!

**Comment by DenverCoder1** [comment]
Seems more like a Firefox bug than anything, but I have now moved most of the styling from inline CSS to be SVG attributes (#355, #356), so hopefully this fixes the issue.

Might need to wait some time to see the results on cached URLs.

**Comment by rafael-c-alexandre** [comment]
It appears to be fine now. Thanks!
