### ISSUE TITLE
gh-{dark, light}-mode-only property flag feature

### ISSUE THREAD

**Issue by brunolnetto** [DenverCoder1/github-readme-streak-stats#359]
**Is your feature request related to a problem? Please describe.**
Your [fellows](https://github.com/anuraghazra/github-readme-stats) provide a `#`-flag on URL query to enable the marked-up markdown only on specific `gh-mode`. For reference, look at my [README](https://github.com/brunolnetto/brunolnetto). Is it possible on `github-readme-streak-stats`?

**Describe the solution you'd like**
Dark and light mode properties theme property flags

**Comment by DenverCoder1** [comment]
That is a built-in feature of GitHub and will work with any image including streak stats.

It's also mentioned in the Streak Stats documentation here:
https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/faq.md#how-do-i-make-different-images-for-dark-mode-and-light-mode

Also see the GitHub documentation on it here:
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to
