### ISSUE TITLE
Older streak (longest) is not being showed

### ISSUE THREAD

**Issue by sushant-sinha** [DenverCoder1/github-readme-streak-stats#363]
**Description**

A brief description of the question or issue:

So my current streak is of 231 days
April 15 2022-December 1 2022

But... my longest streak is ~470 days
December 23 2020 - April 9 2022

You can check my readme file here: https://github.com/sushant-sinha/sushant-sinha/blob/main/README.md

Is there any new setting/feature that I'm not aware of which would have by default taken this year-2022's stats only

![image](https://user-images.githubusercontent.com/60685656/205128300-ba2305d8-b22f-4560-8045-703fe59175f3.png)

Thanks!

**Comment by DenverCoder1** [comment]
It's simply an issue with the GitHub API being inconsistent as usual. Unfortunately, there's nothing I can do about it.

It may start showing correctly eventually if you wait.

GitHub sometimes shows the correct numbers, but may sometimes show 0 for a day even when there are stats on the contribution graph. It may be a timezone issue or something else. If you can identify which days GitHub may be returning 0 contributions for, you can make [fake contributions](https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/faq.md#why-doesnt-my-streak-stats-match-my-contribution-graph) to try making it stop showing as 0. Other than that, I don't have any other suggestions.

**Comment by DenverCoder1** [comment]
I tried visiting the image directly and I'm seeing 473 now. I didn't change anything related to that, so like I said, it's inconsistent because of GitHub.

![image](https://user-images.githubusercontent.com/20955511/205138333-6f577f9f-0ef0-4544-937a-8676b58eeef7.png)

**Comment by sushant-sinha** [comment]
Yup! its working now.

Don't know what makes this inconsistent though... Anyways... Thanks!

**Comment by DenverCoder1** [comment]
Basically, sometimes GitHub says there were contributions on a given day, and sometimes they say there weren't.

I can only make the stats as GitHub's API allows.
