### ISSUE TITLE
Issue with Streak update

### ISSUE THREAD

**Issue by SDBranka** [DenverCoder1/github-readme-streak-stats#400]
**Describe the bug**

**To Reproduce**

1. When I use the "&hide_border=true" parameter the date shown and the streak count are both incorrect.
2. When I omit that parameter the issue does not present itself.
3.  The included screenshot is of my page while I have both states active

**Expected behavior**
I expect to see the dates and streak represented accurately.

**Screenshots**
![Streak Screenshot 2023-01-01 201810](https://user-images.githubusercontent.com/40327959/210189487-a055586d-2a6e-469a-b62f-53c97551b5bf.png)

**Desktop (please complete the following information):**

- OS: windows 11
- Browser Firefox and brave

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DenverCoder1** [comment]
GitHub caches the images on their servers, so changing the URL will make it update immediately, otherwise, you just have to wait for GitHub to fetch the image again which can be up to a few hours

**Comment by DenverCoder1** [comment]
See also #95, #114, #178
