### ISSUE TITLE
Streak stats don't show

### ISSUE THREAD

**Issue by MitkoVtori** [DenverCoder1/github-readme-streak-stats#404]
Hi, there's problem with the streak stats.
They don't show. I've used them for two months and for first time I have this problem.
When I go to the webstie to see if the contrasts are the problem, even there everything is wrong. 
It doesn't show the card, it shows only the logo of unloaded image.
Also, the website is loading so slow.

**Comment by MitkoVtori** [comment]
Bug fixed, closing issue as answered.

**Comment by Saqib92** [comment]
still facing this issue.

**Comment by MitkoVtori** [comment]
> still facing this issue.

it's fixed, I can see them.

**Comment by Saqib92** [comment]
> > still facing this issue.
> 
> it's fixed, I can see them.

did you do anything or changed anything?

**Comment by MitkoVtori** [comment]
> > > still facing this issue.
> > 
> > 
> > it's fixed, I can see them.
> 
> did you do anything or changed anything?

No.
