### ISSUE TITLE
[ERROR] [Deployment] .env was not found. Check Contributing.md for details.

### ISSUE THREAD

**Issue by shariqmalik** [DenverCoder1/github-readme-streak-stats#419]
**Describe the bug**
I'm having issue with the deployment on vercel

**To Reproduce**
Steps I followed for deployment:

1. Sign in to Vercel or create a new account at https://vercel.com/
2. Clone this repository with git clone https://github.com/DenverCoder1/github-readme-streak-stats.git
3. You may also fork the repository and clone your fork instead if you intend to make changes
4. Enter the directory with cd github-readme-streak-stats
5. Switch branches to the vercel branch with git checkout vercel
6. Make sure you have the [Vercel CLI](https://vercel.com/download) installed
7. Run vercel and follow the prompts to link your Vercel account and select a project name
8. The app will be deployed to <project-name>.vercel.app
9. Visit [this link](https://github.com/settings/tokens/new?description=GitHub%20Readme%20Streak%20Stats) to create a new Personal Access Token (no scopes required)
10. Scroll to the bottom and click "Generate token"
11. Visit the [Vercel dashboard](https://vercel.com/dashboard) and select your project, then click "Settings", then "Environment Variables".
12. Add a new variable with the key TOKEN and the value as your token from step 9 and click "Save".

**Screenshots**
Having the following .env related error.
![image](https://user-images.githubusercontent.com/19536819/212678492-086b545b-f45d-4905-af16-8583cf370f40.png)

**Comment by trinib** [comment]
@shariqmalik was getting this issue as well. What worked for me just  rename `.env.example` to `.env` , then add in your KEY token in file and save changes. Then vercel should update `.env` file if linked with repository

**Comment by DenverCoder1** [comment]
Steps 11 and 12 add the token to the app. After you do those steps it should work

**Comment by Klay4** [comment]
> @shariqmalik was getting this issue as well. What worked for me just rename `.env.example` to `.env` , then add in your KEY token in file and save changes. Then vercel should update `.env` file if linked with repository
> 
> FYI make sure your repo is private so token would not be exposed to public

I've created a .env file with the token and then runned `vercel` but it still doesn't work

**Comment by trinib** [comment]
> > @shariqmalik was getting this issue as well. What worked for me just rename `.env.example` to `.env` , then add in your KEY token in file and save changes. Then vercel should update `.env` file if linked with repository
> > 
> > FYI make sure your repo is private so token would not be exposed to public
> 
> I've created a .env file with the token and then runned `vercel` but it still doesn't work
> ![immagine](https://user-images.githubusercontent.com/39599216/212781075-92abc906-2ef4-4668-8fbb-1f81a08e4c8b.png)
> 
> 
> I have even added the token to the app
> ![immagine](https://user-images.githubusercontent.com/39599216/212780970-eb522c7d-ee63-433e-af72-a6c158fcd1f7.png)
> 
> 
> ![immagine](https://user-images.githubusercontent.com/39599216/212781113-c3ff2f7d-3b48-408f-a98e-ac859dde0fdf.png)
> 

I looks like you issue is, you are in the repo main branch and not the branch name "vercel"

**Comment by Klay4** [comment]
> > > @shariqmalik was getting this issue as well. What worked for me just rename `.env.example` to `.env` , then add in your KEY token in file and save changes. Then vercel should update `.env` file if linked with repository
> > > FYI make sure your repo is private so token would not be exposed to public
> > 
> > 
> > I've created a .env file with the token and then runned `vercel` but it still doesn't work
> > ![immagine](https://user-images.githubusercontent.com/39599216/212781075-92abc906-2ef4-4668-8fbb-1f81a08e4c8b.png)
> > I have even added the token to the app
> > ![immagine](https://user-images.githubusercontent.com/39599216/212780970-eb522c7d-ee63-433e-af72-a6c158fcd1f7.png)
> > ![immagine](https://user-images.githubusercontent.com/39599216/212781113-c3ff2f7d-3b48-408f-a98e-ac859dde0fdf.png)
> 
> It looks like your issue is, you are in the repo main branch and not the branch name "vercel"

I'm in the vercel branch 
![immagine](https://user-images.githubusercontent.com/39599216/212790576-9df5a576-1462-4979-8cc7-e95f6dadbaf0.png)

**Comment by trinib** [comment]
I mean edit .env file in `vercel branch` in the repo that is connected .. it looked like from in the screenshot you did it in main branch. If still not working just make a private repo with vercel branch contents, connect repo in vercel and then rename file(.env.example) and add key token and save

**Comment by Klay4** [comment]
> I mean edit .env file in `vercel branch` in the repo that is connected .. it looked like from in the screenshot you did it in main branch. If still not working just make a private repo with vercel branch contents, connect repo in vercel and then rename file(.env.example) and add key token and save

I've just created a new private repo, added the .env with the token in the vercel branch, recreated the project on verce, changed the Production Branch in vercel, added the token even in the vercel panel, but still don't working...
![immagine](https://user-images.githubusercontent.com/39599216/212793502-80ba8a40-ad40-431f-9b19-72bd7e51ec95.png)

**Comment by Klay4** [comment]
I've alerady turned off "Include source files outside of the Root Directory in the Build Step". Now i try to recreate the repo with the only vercel content as main branch but i think that nothing will change...

**Comment by shariqmalik** [comment]
@trinib I tried but just like @Klay4 still having the same issue.

**Comment by shariqmalik** [comment]
Let me know if there is anything I'm still missing.

![image](https://user-images.githubusercontent.com/19536819/212853051-758012d4-0dd5-4bd1-b15f-05ccf7ac21ba.png)

![image](https://user-images.githubusercontent.com/19536819/212853150-9097ccb7-160f-4ee1-9196-dda24a1bec4f.png)

![image](https://user-images.githubusercontent.com/19536819/212853262-0f6f849d-4243-487c-bb38-1652e101d365.png)

![image](https://user-images.githubusercontent.com/19536819/212853418-3b1617ae-50f6-4c9e-9d79-9353c78c91c5.png)

**Comment by shariqmalik** [comment]
@Klay4 
Things worked for me.

1. Cloned or mirror this repository into a new private repository.
2. Import private repo to vercel.
3. Added TOKEN in Environment Variables, unchecked _Include resource files outside of Root Directory..._, and Hit deploy.
4. After deployment it won't work as the branch is main. To fix it go back to **Settings** -> **Git** and change the branch name from **main** to **vercel**.
5. To change the production branch, you must now push a commit.
  I just added TOKEN to the .env file and commit it. _I have no idea why I did this as I already added TOKEN to the environment variables._
6. The Production branch changed to **vercel** and it's working now.

Thanks a lot, @trinib & @DenverCoder1

**Comment by DenverCoder1** [comment]
I have added to the steps to redeploy the app after setting the environment variable as it seems to be required (https://github.com/DenverCoder1/github-readme-streak-stats/commit/9b0767eada70dd47180e41afe6205eb60755ac08).

Also, I'd recommend against putting active tokens in a GitHub repo even if it's private. If it's private it's less likely to be an issue, but files in GitHub repos are not a secure way of storing secrets. `.env` should only be used if running locally or on a dedicated server. If using a service, such as Heroku or Vercel, that provides other methods of inputting secrets, the service's recommended method should be used.
