### ISSUE TITLE
The Total Contributions suddenly changed to 2k from 10k

### ISSUE THREAD

**Issue by hantsy** [DenverCoder1/github-readme-streak-stats#421]
**Describe the bug**
I am not sure if there is a upgrade in these days, my *Total Contributions* is changed to 27xx from a 10xxx.

**To Reproduce**
Check https://github.com/hantsy

**Comment by DenverCoder1** [comment]
The GitHub API sometimes doesn't return the data properly, possibly due to rate limiting.

You can either wait for the next time it refreshes or try self-hosting to use your own GitHub token.
