### ISSUE TITLE
Clear advanced properties when changing theme

### ISSUE THREAD

**Issue by timagixe** [DenverCoder1/github-readme-streak-stats#433]
**Is your feature request related to a problem? Please describe.**
When some advanced props are set and user tries to change the theme - advanced props are not reset to default (i.e. removed) and the theme styles are not applied (actually they are overwritten by advanced props).

**Describe the solution you'd like**
Reset advanced props when theme is changed.

**Describe alternatives you've considered**
N/A

**Additional context**

https://user-images.githubusercontent.com/60817786/215271526-9f7853a4-a538-48b0-9594-f37e2a038a78.mov

**Comment by DenverCoder1** [comment]
I'm not sure I agree with this. If the user set specific overrides, I would think they should still apply. If the user does not want them, they can remove the advanced properties themselves without much difficulty. The way it is could also help prevent loss of work.

**Comment by DenverCoder1** [comment]
Maybe an alternative solution could be to have a button to clear advanced options?

There are only 10 options, so I don't think clearing them one-by-one is a significant amount of effort, but if being able to clear them quickly seems important, perhaps it could be added as an action next to the export button.

Feel free to let me know what you think.

**Comment by DenverCoder1** [comment]
Sounds good to me.

I'm not such a huge fan of confirm(), but there are some alternatives such as sweetalert2 that are nicer. I'm not really sure that it's all that necessary here though.

A "clear" button that calls the function you have written already seems like it would be sufficient.

I'm open to hearing what you think and I look forward to reviewing.

**Comment by timagixe** [comment]
I have pushed changes to the #438. Here is how they look:

https://user-images.githubusercontent.com/60817786/215566468-7a0ce6c9-5d8a-4817-a786-9399280e3c78.mp4

Let me know whether the tooltip over disabled clear button is needed.

**Comment by DenverCoder1** [comment]
I think this looks great :+1:
