### ISSUE TITLE
Add property to disable animation

### ISSUE THREAD

**Issue by everman32** [DenverCoder1/github-readme-streak-stats#451]
It would be nice to add a property responsible for disabling animations, something like `disable_animations=true`, since in the case of a large README.md file with many statistics, animations slow down rendering.
Examples from known statistics:

- [Stats Card Exclusive Options](https://github.com/anuraghazra/github-readme-stats#stats-card-exclusive-options)
- [Language Card Exclusive Options](https://github.com/anuraghazra/github-readme-stats#language-card-exclusive-options)

As you can see, in both cases, the `disable_animations` property is available, which defaults to false.

**Comment by DenverCoder1** [comment]
Thanks for the suggestion.

We already have "png" mode which removes animations (`&type=png`).

Since using SVG is more efficient, adding this option would allow the speed and efficiency of SVG while still providing this functionality.

Let me know what you think and if it's necessary to have. It's a simple change given the already existing code.

**Comment by everman32** [comment]
But in this case, the background of the statistics changes, which I consider unaesthetic, since the background of the statistics and the github in my case are identical🤨.

SVG:
![svg](https://user-images.githubusercontent.com/83178388/218749912-e19d5416-9984-4676-8028-01304d2d26ff.png)
PNG:
![png](https://user-images.githubusercontent.com/83178388/218750171-22c6620c-e4de-4836-97eb-4a0f554675f4.png)

**Comment by DenverCoder1** [comment]
It looks the same to me. Can you send a screenshot showing the differences?

![Screenshot_20230215-002610](https://user-images.githubusercontent.com/20955511/218877445-2dfae314-c2b8-4d73-ad4b-9cda114721fe.png)

**Comment by DenverCoder1** [comment]
The background transparency issue should now be fixed in #453. It seems like a bug with inkscape but I made a workaround to treat any fully transparent colors as "none", so your use case should work now.

**Comment by everman32** [comment]
I haven't looked at the code, but is it possible to disable the animation but still keep the svg type?  If possible, it would certainly be cool to add a `disable_animations` option.  However, if this is not possible, then there is no point in adding this property, which will do the same thing as `type=png`.

**Comment by DenverCoder1** [comment]
Yes, I've created #452 which is to add `disable_animations` which will keep the SVG type
