### ISSUE TITLE
failing to load image

### ISSUE THREAD

**Issue by Ntshangase** [DenverCoder1/github-readme-streak-stats#461]
**Describe the bug**
The image with all the stats information is failing to load, I have refreshed a couple of times but it still doesn't load. It was working fine yesterday.

**To Reproduce**

1. Go to 'https://github.com/Ntshangase'
2. Click on '.....'
3. Scroll down to 'my GitHub stats'

**Expected behavior**
The Github streak Image will fail to load.

**Screenshot
![Screenshot (51)](https://user-images.githubusercontent.com/62051440/220655868-494c5e6b-6d13-4a3f-a58e-4eefea7a4fcb.png)
s**

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version Version 104.0.5112.81 (Official Build) (64-bit)

**Additional context**
for me to get the GitHub streak I used online demo version from [http://streak-stats.demolab.com/demo/](url) I just copied the link and pasted it in my Readme.md with all my stats, And it was working fine yesterday. I was using my laptop that's why I removed the smartphone information above.

**Comment by anserwaseem** [comment]
Facing same issue

**Comment by MitkoVtori** [comment]
This must be resolved!

**Comment by DenverCoder1** [comment]
I've restarted it on Heroku and it seems to be working better for now.

I'll probably need to move it to a new host eventually.

**Comment by MitkoVtori** [comment]
> I've restarted it on Heroku and it seems to be working better for now.
> 
> I'll probably need to move it to a new host eventually.

Well, it works for me currently.

**Comment by DenverCoder1** [comment]
The issue seems to be the request timing out since it takes too long to fetch all the contributions

**Comment by Ntshangase** [comment]
It's working now, Thanks.
