### ISSUE TITLE
Incorrect total contribution counter

### ISSUE THREAD

**Issue by f-karagoz** [DenverCoder1/github-readme-streak-stats#465]
**Describe the bug**
Total contribution number is not correct. It shows significantly less value.

**To Reproduce**
1. Visit a gitHub profile.

**Expected behavior**
Contribution number shows relatively accurate data.

**Screenshots**
![Screen Shot 2023-02-28 at 00 50 01 AM](https://user-images.githubusercontent.com/30375635/221694152-74b4e130-60e7-449b-b931-11e58fa769e5.png)

**Desktop:**

- OS: macOS 12.6.2
- Browser: Opera 
- Version: 95.0.4635.46

**Comment by DenverCoder1** [comment]
Sometimes requests time out since the server can't handle so many requests every second.

Only suggestion I can make is to self-host with your own GitHub token or wait until the cache expires and GitHub will fetch the stats again.
