### ISSUE TITLE
Streak reset incorrectly

### ISSUE THREAD

**Issue by Luminous-Coder** [DenverCoder1/github-readme-streak-stats#470]
**Describe the bug**
The streak got reset though there are contributions.

**To Reproduce**

1. Visit a GitHub profile.

**Expected behavior**
The streak begins on a correct date.

**Screenshots**
![streak](https://user-images.githubusercontent.com/84374077/224653289-74130321-af43-4368-a460-642b0d93ab7a.png)
![contributions](https://user-images.githubusercontent.com/84374077/224653392-3ec2bf93-a0f2-4e7b-8d23-ca43598e7fc4.png)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser: Firefox
- Version: 109.0.1

**Smartphone (please complete the following information):**

- Device: OPPO CPH2015
- OS: ColorOS 6.1.2 (Android 9)
- Browser: Firefox
- Version: 110.1.0

**Additional context**
I know the update is lag but this problem has appeared for days, so I think it's a bug.

**Comment by DenverCoder1** [comment]
The stats show whatever the GitHub API returns so there's nothing I can do about this. Check this possible solution the FAQ:

https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/faq.md#why-doesnt-my-streak-stats-match-my-contribution-graph

**Comment by Luminous-Coder** [comment]
Oh, I see.
