### ISSUE TITLE
Using custom option for label color of dates crashes the block

### ISSUE THREAD

**Issue by Falcion** [DenverCoder1/github-readme-streak-stats#471]
**Describe the bug**
When you're using the advanced custom option to define dates label's color, it sends you an "API error" which is not true, because if you delete "DATES=" param it works perfectly: I thought that I'm the imbecile in the room, but if you use demolab constructor, it also causes this problem.

**Reproduce:**

Just add some date parameter in your image request, which is like (for example I use my account):

```txt
https://streak-stats.demolab.com/?user=Falcion
-->
https://streak-stats.demolab.com?user=Falcion&dates=989898
```

**Expected behavior:**

Output of block with coloured dates label (working block).

**Comment by Falcion** [comment]
Gone to issues too fast and can't wait: everything is fine by now, sorry.

**Comment by DenverCoder1** [comment]
Yeah, seems like an issue due to heavy traffic to the server. [Deploying on your own](https://github.com/DenverCoder1/github-readme-streak-stats#-deploying-it-on-your-own) might help, but there isn't much I can do to fix it at the moment.
