### ISSUE TITLE
Add support for GitLab contributions  

### ISSUE THREAD

**Issue by noverby** [DenverCoder1/github-readme-streak-stats#477]
It would be nice, if the project supported fetching contributions from GitLab in addition to GitHub contributions, for users of both platforms.

**Comment by chrisK824** [comment]
@noverby that's a feature you can get from other repos which can fetch commits from other platforms. I have used such one and modified for my needs to include commits from repos I contribute in other platforms than github. You can have a look and make use of it if you like it :) https://github.com/chrisK824/git-commits-import/blob/main/README.md
