### ISSUE TITLE
Healthy option for streak counter

### ISSUE THREAD

**Issue by chrisK824** [DenverCoder1/github-readme-streak-stats#484]
**Is your feature request related to a problem? Please describe.**
This is not a problem really but just a suggestion to include an option for streak counting. Idea is a feature that could be enabled optionally and would count streak days only from week - labor days and not weekends. That "healthy" option would allow the streak to be continued in actual work days and not get lost just cause one didn't contribute in their off days.

**Describe the solution you'd like**
Solution would be provided with a kind of flag, e.g 'healthy=True' and of course this would be reflected on the image generated to be declared so not to be confused with the ones that don't use the filter.

**Comment by DenverCoder1** [comment]
This is related to #408

**Comment by chrisK824** [comment]
Indeed @DenverCoder1 , didn't catch that one, I guess you can close this then, cheers!

**Comment by DenverCoder1** [comment]
Feel free to let me know if you have any thoughts or suggestions on this implementation

* #490

https://github-readm-feat-exclu-meca8s.herokuapp.com/demo/

**Comment by chrisK824** [comment]
Seems legit @DenverCoder1 :) It will cover most needs as those three days are the most possible days off for most people. Maybe all week days should be provided as options though.

**Comment by DenverCoder1** [comment]
All options are possible with the query parameter, but I only listed a few on the demo site to make implementing it easier

**Comment by DenverCoder1** [comment]
Thanks for the feedback. It uses checkboxes now, so it's more flexible.

**Comment by chrisK824** [comment]
Great :)
