### ISSUE TITLE
Add option to hide total contributions

### ISSUE THREAD

**Issue by boldandbrad** [DenverCoder1/github-readme-streak-stats#491]
**Is your feature request related to a problem? Please describe.**

I use https://github.com/anuraghazra/github-readme-stats to show total contributions on my profile. I’d like to not have duplicate data between the two info graphics. In my mind streak-stats should have an option to only show info related to the streaks.

**Describe the solution you'd like**

I’d like to see a `hide_contribs` option that allows the user to not display the total contributions panel.

**Describe alternatives you've considered**

I could technically hide the contributions from the other info graphic, but for my use case this is not ideal.

**Comment by DenverCoder1** [comment]
Thanks for the suggestion!

**Comment by DenverCoder1** [comment]
You can now remove sections of the card using the following options:

|         Parameter          |                     Details                      |                                              Example                                               |
| :------------------------: | :----------------------------------------------: | :------------------------------------------------------------------------------------------------: |
| `hide_total_contributions` | Hide the total contributions (Default: `false`)  |                                         `true` or `false`                                          |
|   `hide_current_streak`    |    Hide the current streak (Default: `false`)    |                                         `true` or `false`                                          |
|   `hide_longest_streak`    |    Hide the longest streak (Default: `false`)    |                                         `true` or `false`                                          |

The `card_width` option can also be used to remove some of the extra padding.

```md
https://streak-stats.demolab.com/?user=boldandbrad&hide_total_contributions=true&card_width=330
```

![image](https://user-images.githubusercontent.com/20955511/232756461-ff64c866-a557-4037-9f31-355c9e764fc1.png)
