### ISSUE TITLE
Add option to specify output width

### ISSUE THREAD

**Issue by boldandbrad** [DenverCoder1/github-readme-streak-stats#492]
**Is your feature request related to a problem? Please describe.**

I use https://github.com/anuraghazra/github-readme-stats in my profile readme as well. I like using this in conjunction with streak-stats, but they output different widths. While readme-stats does support a width option, streak-stats does not.

**Describe the solution you'd like**

A `width` option that specifies the output width of the info graphic in pixels (similar to readme-stats).

**Describe alternatives you've considered**

Use the readme-stats width option to match streak-stats, but this is not ideal if I’d like them both to be smaller.

**Comment by DenverCoder1** [comment]
Shrinking the width is not recommended since there won't be much padding around the text, but I can implement this option without much trouble
