### ISSUE TITLE
Days jumped down from 32 to 9

### ISSUE THREAD

**Issue by Katrina-Dierking** [DenverCoder1/github-readme-streak-stats#501]
**Describe the bug**
The counter went down from 32 to 9 for no reason today. 

**To Reproduce**

1. Go to '..https://github.com/Katrina-Dierking'
2. Click on '.README'
3. Scroll down to bottom of the page. See the green squares (32 as of today)
4. See streak counter is showing 9. This happened today (4.18.23)

**Expected behavior**
The streak counter should be showing 32 today.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DenverCoder1** [comment]
![image](https://user-images.githubusercontent.com/20955511/232986901-c254948a-1126-41d2-a986-54c2cdc596f6.png)

Your contribution graph shows no contributions on April 9, possibly the contributions are private or your timezone doesn't match the timezone the contributions were fetched for.

The contribution counts are collected directly from the GitHub API so there isn't much that can be done to fix this.

You could also try adding a new commit on April 9 to get the streak to fix itself, more info in the FAQ.

https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/faq.md#why-doesnt-my-streak-stats-match-my-contribution-graph
