### ISSUE TITLE
Contributions are not counting all the way back to first contributions

### ISSUE THREAD

**Issue by chrisK824** [DenverCoder1/github-readme-streak-stats#503]
**Describe the bug**
Contributions are not counting all the way back to first contributions

**To Reproduce**
Compare contributions shown from API for my account
against oldest contributions from my account

**Expected behavior**
Oldest contribution should be on Nov 9, 2019 instead

**Screenshots**
[SVG for my account](https://streak-stats.demolab.com/?user=chrisK824&theme=highcontrast)

![image](https://user-images.githubusercontent.com/79946379/233350182-abb09139-367a-4998-be84-86e473389d2a.png)

**Desktop (please complete the following information):**

- OS: macOs
- Browser chrome
- Version 112.0.5615.121 (Official Build) (arm64)

**Comment by DenverCoder1** [comment]
Were these contributions imported from another source?

According to the [GitHub API](https://api.github.com/users/chrisK824) your account was created on March 2, 2021.

Currently years before the account creation date are excluded in order to limit the number of requests - see #449.

**Comment by chrisK824** [comment]
I see @DenverCoder1 . Yeah I noticed that just right now in the GraphQL explorer. Indeed I have used a tool to import mocked commits from other sources which took timestamp before my account creation. 

So I see in the ticket above that this was causing a problem to go all the way back until no contributions found, crap :p 

Anyways, I opened a support ticket to ask if it is possible to change the created at timestamp in user profile, as this would be more sensible anyways.

Thanks for the quick reply :)

**Comment by DenverCoder1** [comment]
Yeah, it used to go back all the way to the first year with contributions, but that was causing the image to not load when there are too many years to fetch, hence the change in #449.

One possibility which was suggested in #448 was to create a way to override the minimum contribution year, or possibly in another way specify years to check that are before the account creation date. I don't know if it overcomplicates things though as it's probably not that common to need that feature.

**Comment by DenverCoder1** [comment]
Sure, feel free to work on it. :+1: 

It seems to me that the best approach would probably be to add a parameter to the getContributionGraphs function that can take the override or null, and if it's not null, the function would create the yearsToRequest range from the override instead of the userCreatedYear.
