### ISSUE TITLE
Incorrect Demo Site link in Readme

### ISSUE THREAD

**Issue by RiteshK-611** [DenverCoder1/github-readme-streak-stats#518]
**Describe the bug**

The demo site link starts with "http://"

**Expected behavior**

The demo site link should be change to "https://"

**Screenshots**

![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/61982298/b06d74e9-e285-4c99-a01b-dbec2cb10dbe)

**Comment by TRIPLE-ADE** [comment]
Could you please assign this issue to me? I would like to contribute and work on resolving it.

**Comment by DenverCoder1** [comment]
@TRIPLE-ADE Great, feel free to open a pull request. If you have any questions feel free to let me know :+1:

**Comment by TRIPLE-ADE** [comment]
Thank you for the opportunity
