### ISSUE TITLE
Streak interrupted suddenly while it was counting fine 

### ISSUE THREAD

**Issue by chrisK824** [DenverCoder1/github-readme-streak-stats#524]
**Describe the bug**
Streak seems broken in my account even though Github contribution graph says otherwise.

**To Reproduce**

1. Go to my account: https://github.com/chrisK824
2. Click on 11th May in contributions graph
3. Confirm that 11th of May has one contribution

**Expected behavior**
Expected streak not to break on this day

**Screenshots**
https://streak-stats.demolab.com/?user=chrisK824&theme=highcontrast&starting_year=2010
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DenverCoder1** [comment]
The stats show whatever the GitHub API returns so it's a GitHub problem and not something that can be fixed. Check this possible solution the FAQ:

https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/faq.md#why-doesnt-my-streak-stats-match-my-contribution-graph
