### ISSUE TITLE
Add Catppuccin Theme

### ISSUE THREAD

**Issue by abhishekmj303** [DenverCoder1/github-readme-streak-stats#535]
**Describe your theme in detail**
This is to add the [Catppuccin Theme](https://github.com/catppuccin/catppuccin), a community-driven pastel theme that aims to be the middle ground between low and high contrast themes. It consists of 4 soothing warm flavors.

**Include a screenshot / image**
Latte:

![catppuccin-latte](https://github.com/DenverCoder1/github-readme-streak-stats/assets/85760664/358a8a31-4ffc-4535-a617-840926ecd4f0)

Frappé:

![catppuccin-frappe](https://github.com/DenverCoder1/github-readme-streak-stats/assets/85760664/daa7bd60-1e83-4b4e-8afc-65644055235e)

Macchiato:

![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/85760664/15d74ba2-746a-4efd-b2f5-bc2db87b7c10)

Mocha:

![catppuccin-mocha](https://github.com/DenverCoder1/github-readme-streak-stats/assets/85760664/9f965d12-2013-48c9-b3a8-e9717b1c4e43)

**Color palette**
```
[
"catppuccin-latte" => [
    "background" => "#EFF1F5",
    "border" => "#E4E2E2",
    "stroke" => "#E4E2E2",
    "ring" => "#179299",
    "fire" => "#179299",
    "currStreakNum" => "#8839EF",
    "sideNums" => "#4C4F69",
    "currStreakLabel" => "#8839EF",
    "sideLabels" => "#4C4F69",
    "dates" => "#5C5F77",
    "excludeDaysLabel" => "#5C5F77",
],
"catppuccin-frappe" => [
    "background" => "#303446",
    "border" => "#E4E2E2",
    "stroke" => "#E4E2E2",
    "ring" => "#81C8BE",
    "fire" => "#81C8BE",
    "currStreakNum" => "#CA9EE6",
    "sideNums" => "#C6D0F5",
    "currStreakLabel" => "#CA9EE6",
    "sideLabels" => "#C6D0F5",
    "dates" => "#B5BFE2",
    "excludeDaysLabel" => "#B5BFE2",
],
"catppuccin-macchiato" => [
    "background" => "#24273A",
    "border" => "#E4E2E2",
    "stroke" => "#E4E2E2",
    "ring" => "#8BD5CA",
    "fire" => "#8BD5CA",
    "currStreakNum" => "#C6A0F6",
    "sideNums" => "#CAD3F5",
    "currStreakLabel" => "#C6A0F6",
    "sideLabels" => "#CAD3F5",
    "dates" => "#B8C0E0",
    "excludeDaysLabel" => "#B8C0E0",
],
"catppuccin-mocha" => [
    "background" => "#1E1E2E",
    "border" => "#E4E2E2",
    "stroke" => "#E4E2E2",
    "ring" => "#94E2D5",
    "fire" => "#94E2D5",
    "currStreakNum" => "#CBA6F7",
    "sideNums" => "#CDD6F4",
    "currStreakLabel" => "#CBA6F7",
    "sideLabels" => "#CDD6F4",
    "dates" => "#BAC2DE",
    "excludeDaysLabel" => "#BAC2DE",
],
]
```

Are you going to add the theme?

- [x] Check for yes

**Comment by abhishekmj303** [comment]
I am not sure how to add the screenshots in the `docs/themes.md`. They contain some github url and there is no folders to put the images.

**Comment by DenverCoder1** [comment]
> I am not sure how to add the screenshots in the `docs/themes.md`. They contain some github url and there is no folders to put the images.

You can just right click on an image in the GitHub issue and do "copy image address"
