### ISSUE TITLE
Change color picker in demo site to support opacity

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-streak-stats#54]
Currently the color picker is the default HTML color picker which, as of now, does not support setting the opacity (alpha channel).

Since transparent cards and semi-transparent cards are possibilities people may want to use, the demo site should support picking colors with transparency.

**Comment by DenverCoder1** [comment]
Possible implementation: https://jscolor.com/ (uses input element)

**Comment by IvoLondon** [comment]
I could give this a go if it hasn't been taken?

**Comment by DenverCoder1** [comment]
@IvoLondon That would be great! If you have any questions, feel free to ask!

**Comment by IvoLondon** [comment]
I need your thoughts on something I just found out - in order to add the opacity controller , the colour needs to be in a RGBA format. The queries in request `const imageURL = `${window.location.origin}?${query}`;` are encoded and passed, but I suspect that a HEX is expected instead. Would you be able to amend this on the backend side or should I find a way to convert it before the request is being made? @DenverCoder1

**Comment by DenverCoder1** [comment]
@IvoLondon Making the query be in 6-digit HEX for opaque colors and 8-digit HEX for transparent colors would be the best. Although I haven't tried it, it seems like https://jscolor.com/ makes the value automatically in HEX, but the "#" will need to be removed (and the "FF" if it ends with "FF").

**Comment by IvoLondon** [comment]
#58

**Comment by IvoLondon** [comment]
Alright, I will sort this out and I will let you know. I've created a pull request, in case you want to see the changes - #58 (not sure if it was supposed to be done, when I'm fully ready?). Thanks!

**Comment by DenverCoder1** [comment]
Looks good, instead of "rgba" in the DOMContentLoaded listener, you can use "hexa" to make it automatically use HEX.

**Comment by DenverCoder1** [comment]
If you can't find a way to easily make it 6 digits when there's no transparency, it's perfectly fine to keep it as 8-digit HEX for all colors.
