### ISSUE TITLE
Longest Streak number is wrong

### ISSUE THREAD

**Issue by Shoaib19** [DenverCoder1/github-readme-streak-stats#540]
**Describe the bug**
I have created the commit streak from Jan 23,2023 to April 12,2023 which was 101 days but currently my max streaks reduce to 80

**Expected behavior**

it should show longest steak on my profile of 101 but it is showing 80.

**Desktop (please complete the following information):**

- OS: Mac
- Browser chrome

**Comment by DenverCoder1** [comment]
Jan 23,2023 to April 12,2023 including both ends is 80 days, unless I misunderstood your question, it seems like it is correct.

![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/20955511/d5d5031a-61bd-435b-b6c8-1d3fbfb18a7e)

**Comment by Shoaib19** [comment]
@DenverCoder1  Oh yes but why it was showing previously the 101 on longest streaks, I know when you delete repo commits also vanished but I didn't deleted those repos, can you track the cause why it was showing 101 before?

**Comment by DenverCoder1** [comment]
I don't know the exact reason it would have changed, but the results displayed represent whatever the GitHub API returns.

It's possible to manually add commits to fill in the dates that are missing if you want, there's more info in the [FAQ](https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/faq.md#why-doesnt-my-streak-stats-match-my-contribution-graph).

**Comment by Shoaib19** [comment]
I think I have deleted some commits when I deleted the repo.
