### ISSUE TITLE
The daily streaks on README.md for a GitHub profile are not working.

### ISSUE THREAD

**Issue by whoami-anoint** [DenverCoder1/github-readme-streak-stats#547]
**Bug:**
 The daily streaks on README.md for a GitHub profile are not working.
**Code:**
`[![GitHub Streak](https://streak-stats.demolab.com?user=whoami-anoint&theme=dark)](https://git.io/streak-stats)`
Github Profile: https://github.com/whoami-anoint/whoami-anoint
![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/72187543/22dd5f89-f609-41a1-8b40-7d50aaa95bf0)

**Comment by DenverCoder1** [comment]
The connection to the Heroku server has been a bit slow today. You could always switch to hosting your own copy if you want, but this issue should go away on its own next time GitHub fetches the image.
