### ISSUE TITLE
Issue on displaying stats

### ISSUE THREAD

**Issue by JoaoCioffi** [DenverCoder1/github-readme-streak-stats#549]
### Discussed in https://github.com/DenverCoder1/github-readme-streak-stats/discussions/548

<div type='discussions-op-text'>

<sup>Originally posted by **JoaoCioffi** August  9, 2023</sup>
Hi everyone. 
I've just noticed that my stats were not displaying anymore. I tried to recompile a new setup using the demo lab and now it looks like this:

``` md
[![GitHub Streak](https://streak-stats.demolab.com?user=JoaoCioffi&theme=dark&hide_border=true&fire=25EB00&background=45%2C000000%2C0C167E&ring=25EB00&currStreakLabel=25EB00&sideLabels=25EB00&currStreakNum=FFFFFF&sideNums=FFFFFF)](https://git.io/streak-stats)
```

Are you guys having the same problem? </div>

**Comment by DenverCoder1** [comment]
Issue seems to be resolved
