### ISSUE TITLE
Why it show Could not find a user with that name for my username?

### ISSUE THREAD

**Issue by vishnuprasad0** [DenverCoder1/github-readme-streak-stats#550]
**Description**
https://streak-stats.demolab.com/?user=vishnuprasad0 
shows Could not find a user with that name?
anybody explain how to fix this my account username is same and its a personal user account too

**Comment by DenverCoder1** [comment]
Clicking on that link it appears to work, so it seems like the issue resolved itself. Let me know if you have any other question.
