### ISSUE TITLE
GitHub stats not showing for my profile

### ISSUE THREAD

**Issue by samyakagarwal20** [DenverCoder1/github-readme-streak-stats#551]
I am using the fhe following URL to fetch my github stats - https://github-readme-streak-stats.herokuapp.com/?user=samyakagarwal20

I have also enabled the private contributions under the settings for my contribution graph.

The following is the my contribution chart so far for the months of July - August 2023
![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/40698105/ad72f835-dd2b-4734-873b-2a0963ec1d5b)

I even tried setting the starting_year field in the query parameters as follows
https://github-readme-streak-stats.herokuapp.com/?user=samyakagarwal20&starting_year=2023

But, I'm still not able to see any contribution in my stats.

Please help me out with this issue.

**Comment by DenverCoder1** [comment]
For me it shows your contributions are private, you probably need to change your profile settings

![Screenshot_20230812-224655.png](https://github.com/DenverCoder1/github-readme-streak-stats/assets/20955511/c73310f9-5c7f-468a-add2-9902514a5477)

**Comment by samyakagarwal20** [comment]
I changed the profile settings. Now, it should be visible.

**Comment by DenverCoder1** [comment]
👍 Yes, it works now


The new domain is demolab, I recommend using this link
https://streak-stats.demolab.com/?user=samyakagarwal20

You can customize it here - https://streak-stats.demolab.com/demo/

**Comment by samyakagarwal20** [comment]
![AwesomeMinionsGIF](https://github.com/DenverCoder1/github-readme-streak-stats/assets/40698105/2879d8d2-6b53-4ff7-8c3b-90425a8df289)

Its working now.

Thanks a lot for resolving with issue in a noticeably short amount of time.
