### ISSUE TITLE
The Stats & Streaks on README.md for a GitHub profile is not working.

### ISSUE THREAD

**Issue by purnasth** [DenverCoder1/github-readme-streak-stats#553]
![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/107195487/cb3799af-aff2-41c2-890b-0a908089cb0b)

**Comment by DenverCoder1** [comment]
Can you explain in more detail what the issue is?

It seems like the error in your screenshot is coming from Anurag Hazra's [GitHub Readme Stats](https://github.com/anuraghazra/github-readme-stats) and not from Streak Stats.

**Comment by effordDev** [comment]
I think @purnasth posted the wrong screenshot, @DenverCoder1 here you are.
![Screenshot 2023-08-31 at 9 52 16 AM](https://github.com/DenverCoder1/github-readme-streak-stats/assets/36901822/229000cd-cc56-48b9-b961-08d820a64447)

**Comment by DenverCoder1** [comment]
When there is a lot of traffic to the Heroku server, the GitHub API seems to stop sending back content, likely as a form of ratelimiting.

To avoid this issue, I recommend self-hosting the project. There are steps in the readme, I just added a new method for deploying with Vercel entirely online. It's free and shouldn't take more than a couple minutes to set up.

**Comment by DenverCoder1** [comment]
@effordDev 

This particular issue has resolved itself at least for now. As far as I can tell there isn't much I can do to prevent it from happening besides telling people to use their own access tokens. Feel free to let me know if you have any questions.

![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/20955511/0949073e-75d3-4841-b5f8-4363eacb7dd0)

**Comment by purnasth** [comment]
I'm so grateful that you took the time to explain what occurred to me since I was completely puzzled and lost. I'll make an effort to move the process toward self-hosting.
