### ISSUE TITLE
My GitHub Streaks doesn't display

### ISSUE THREAD

**Issue by Abubakr030109** [DenverCoder1/github-readme-streak-stats#578]
**Describe the bug**
I followed the steps in the README.md, but it doesn't work.

**To Reproduce**
1. Go to https://github.com/Abubakr030109/Abubakr030109 
2. See error

**Expected behavior**
I expect it to always show my streaks.

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Firefox

**Comment by Abubakr030109** [comment]
Thanks for the help, I'll look into that.

**Comment by DenverCoder1** [comment]
It should also start working on its own, which it seems it already has when I view your profile.

There isn't much I can do to prevent it from going down in the future, so self-hosting is still an option to get it to stay up more reliably.
