### ISSUE TITLE
All commits counting towards the streak?

### ISSUE THREAD

**Issue by lombardi-g** [DenverCoder1/github-readme-streak-stats#585]
The following screenshots were both taken Sep 18th. Some commits were via git, some via upload. Github contributions is counting them, but the streak card counts a 2-day streak instead of a 15-day shown in the contributions section.

[![GitHub](https://img.shields.io/badge/GitHub-000?style=for-the-badge&logo=github&logoColor=fff)](https://github.com/lombardi-g/)

![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/127768914/87bbba8e-4696-41ca-be0b-57fa1b39944d)

![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/127768914/970aadfc-48e7-42ec-b142-1bbeb853bf6d)

**Comment by DenverCoder1** [comment]
It should usually match. Sometimes it can take time for the cache to reset, up to a few hours. If it doesn't, there's likely a time zone difference between your profile view and the streak stats. If so, the only thing that can be done is modify or add commits with the dates that are missing. There's more info in docs/faq.md
