### ISSUE TITLE
Add Neon-Dark & Neon-Palenight Themes

### ISSUE THREAD

**Issue by vikasganiga05** [DenverCoder1/github-readme-streak-stats#59]
## Add two new themes for the `github-readme-streak-stats`

Hi, I designed two new version of theme for the **github-readme-streak-stats**. One is `neon-dark` and another one is `neon-palenight`.

---

#### Theme Colors : 
```php
"neon-dark" => [
    "background" => "#020200"
    "border" => "#a8a8a8"
    "stroke" => "#a8a8a8"
    "ring" => "#e41d44"
    "fire" => "#e41d44"
    "currStreakNum" => "#f9dd3c"
    "currStreakLabel" => "#f9dd3c"
    "sideNums" => "#5cadc0"
    "sideLabels" => "#5cadc0"
    "dates" => "#ed7b25"
]
```

![dark-1](https://user-images.githubusercontent.com/74750414/113265824-3393d780-92f2-11eb-88d5-06f46be76ac1.png)
![dark-2](https://user-images.githubusercontent.com/74750414/113265930-4e664c00-92f2-11eb-8038-1494505e6ed5.png)

---

#### Theme Colors : 
```php
"neon-palenight" => [
    "background" => "#212237"
    "border" => "#a8a8a8"
    "stroke" => "#a8a8a8"
    "ring" => "#e41d44"
    "fire" => "#e41d44"
    "currStreakNum" => "#f9dd3c"
    "currStreakLabel" => "#f9dd3c"
    "sideNums" => "#5cadc0"
    "sideLabels" => "#5cadc0"
    "dates" => "#ed7b25"
]
```

![palenight-1](https://user-images.githubusercontent.com/74750414/113266152-8a99ac80-92f2-11eb-8f59-12d4395cc56b.png)
![palenight-2](https://user-images.githubusercontent.com/74750414/113266167-908f8d80-92f2-11eb-85b3-8453a86281e8.png)

**Comment by DenverCoder1** [comment]
Hi @vikasganiga05! These themes look awesome!

Do you plan on making the PR to add them?

**Comment by vikasganiga05** [comment]
> Hi @vikasganiga05! These themes look awesome!
> 
> Do you plan on making the PR to add them?

Yeah sure, I like to work on this :slightly_smiling_face: . Assign it to me.
