### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by wozverine** [DenverCoder1/github-readme-streak-stats#593]
**Describe the bug**
Streak stats fails to load.

**To Reproduce**

1. Go to 'https://github.com/wozverine'
2. Scroll down 
3. See error

**Expected behavior**
Load and show streak stats.

**Screenshots**
![Screenshot 2023-09-21](https://github.com/DenverCoder1/github-readme-streak-stats/assets/23726873/debb0004-b5eb-475c-94d4-f935a770ed22)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 116

**Additional context**
Code commited by [dependabot[bot]] yesterday seems to be the reason for the bug. chore(deps-dev): bump phpunit/phpunit from 9.6.12 to 9.6.13

**Comment by MoinJulian** [comment]
I got the same issue with following informations:

OS: MacOS
Browser Chrome
Version 109

As well as with

OS: IOS
Browser Safari
Version unknown

**Comment by wozverine** [comment]
![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/23726873/ab509f93-1865-4316-9a98-d0a42be3f72e)
Seems to be fixed
