### ISSUE TITLE
How can I host my own instance in Vercel using my forked repo and not create a new one

### ISSUE THREAD

**Issue by chrisK824** [DenverCoder1/github-readme-streak-stats#594]
**Description**

The readme files includes a Vercel deployment button. When following that process and creating a new git repository from this one then all work fine.
However, I already have a fork of this repo in my account as I've contributed a bit some time back. So I don't want to create another one. Instead I'm following the path by importing this fork into vercel project. I 'm using the exact same settings. including the token env variable, however the vercel instance doesn't work and I'm receiving a 404 error.

![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/79946379/07f9fdab-3056-4ad7-b451-6c45ea90fa6a)

**Comment by DenverCoder1** [comment]
Make sure to switch to the `vercel` branch before deploying to Vercel since that branch has the necessary adjustments that needed to be made.

You can push to Vercel using the CLI with `vercel --prod`. There are steps in the readme (second method).

**Comment by chrisK824** [comment]
Thanks @DenverCoder1 , I got the vercel branch from the upstream and I just changed the vercel project to point to that branch. Redeployed and voila, worked like a charm!

**Comment by DenverCoder1** [comment]
Great, feel free to let me know if you have any more questions
