### ISSUE TITLE
Streak Not Showing even after self hosting

### ISSUE THREAD

**Issue by ShinsuSenju** [DenverCoder1/github-readme-streak-stats#598]
Describe the bug
Streak is not showing. i have hosted my own instance on vercel, still its not working

To Reproduce

Go to Github.com
Click on account which had added Github streak option
Scroll down to Github streak
See error
Screenshots
![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/63202411/1f6b71a0-2441-4311-8570-d2de4f6519ef)

**Desktop

OS: Window
Browser: chrome
Smartphone :

Device: Realme
OS: Window
Browser: Chrome

**Comment by DenverCoder1** [comment]
You have a typo in the url, try using

`https://github-readme-streak-stats-topaz-six.vercel.app/?user=shinsusenju`

instead of

`https://https//github-readme-streak-stats-topaz-six.vercel.app/?user=shinsusenju`

**Comment by ShinsuSenju** [comment]
Thanks
