### ISSUE TITLE
Streak not showing after vercel hosting: "failed to retrieve contributions. This is likely a GitHub API Issue"

### ISSUE THREAD

**Issue by yannickBona** [DenverCoder1/github-readme-streak-stats#599]
**Describe the bug**
I hosted my own instance on Vercel following the tutorial but the streak is not showing: "failed to retrieve contributions. This is likely a GitHub API Issue".

**To Reproduce**
You can find the url on my readme profile

![Screenshot 2023-09-27 alle 16 00 11](https://github.com/DenverCoder1/github-readme-streak-stats/assets/105713790/18e54496-6a2f-41ab-92b4-303c36fc4fae)

- OS: MacOS
- Browser Chrome

**Comment by DenverCoder1** [comment]
Maybe check that there is an access token in the environment variables and it is active? It's possible that the error could occur because of an invalid token. It's not likely a rate limit issue unless you are using up all of your rate limit with different tokens in other projects.

**Comment by yannickBona** [comment]
@DenverCoder1 the issue was indeed the Access Token, which was expired and I blindly put it in the Token Section.
Thanks for the precious help!
