### ISSUE TITLE
Hide border Option

### ISSUE THREAD

**Issue by HPaulson** [DenverCoder1/github-readme-streak-stats#6]
Having a `hide_border` option for cards would be pretty nice. Now with dark mode, card borders are pretty intrusive- and overall ugly. Below is an example alongside [Github Readme Stats](https://cdn.seismiccore.com/gFo.png), which does have this option, just for a comparison.
Thanks! :+1: 
![](https://cdn.seismiccore.com/gFo.png)

**Comment by DenverCoder1** [comment]
Thanks for opening the issue! I will get started on this right away.

**Comment by HPaulson** [comment]
Awesome!
