### ISSUE TITLE
Add new theme called `dark-smoky`

### ISSUE THREAD

**Issue by vikasganiga05** [DenverCoder1/github-readme-streak-stats#61]
## Add a new themes for the `github-readme-streak-stats`

Hi, I designed a new theme for the **github-readme-streak-stats**, Which is called as `dark-smoky`.

---

#### Theme Colors : 
```php
"neon-dark" => [
    "background" => "#0b0c10"
    "border" => "#c5c6c7"
    "stroke" => "#c5c6c7"
    "ring" => "#edf5e1"
    "fire" => "#edf5e1"
    "currStreakNum" => "#66fcf1"
    "currStreakLabel" => "#66fcf1"
    "sideNums" => "#edf5e1"
    "sideLabels" => "#edf5e1"
    "dates" => "#45a29e"
]
```

![screenshot-github-readme-streak-stats herokuapp com-2021 04 08-09_34_59](https://user-images.githubusercontent.com/74750414/113967725-38efa580-984f-11eb-9979-5a70bd7db49a.png)
![screenshot-github-readme-streak-stats herokuapp com-2021 04 08-09_35_28](https://user-images.githubusercontent.com/74750414/113967737-3ee58680-984f-11eb-90ec-9d304963fe50.png)

**Comment by DenverCoder1** [comment]
Awesome, would you like to be assigned this issue?

**Comment by vikasganiga05** [comment]
Hi, I like to work on this. Please assign to me :slightly_smiling_face:
