### ISSUE TITLE
Not showing the GitHub Streaks

### ISSUE THREAD

**Issue by Akash3121** [DenverCoder1/github-readme-streak-stats#620]
**Describe the bug**

**To Reproduce**
https://github.com/Akash3121

**Expected behavior**
It should show.

**Screenshots**
![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/87650180/91433da1-1d83-4181-978e-bd61ae8f98ab)
It's showing like this, can some one help me with this please

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows
- Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rumstead** [comment]
I noticed if I enabled `Include private contributions on my profile` I get the same error but with it toggled off everything loads.

**Comment by DenverCoder1** [comment]
https://github.com/DenverCoder1/github-readme-streak-stats/issues/616#issuecomment-1787834794
