### ISSUE TITLE
What type of contributions are counted?

### ISSUE THREAD

**Issue by AkshayAshokCode** [DenverCoder1/github-readme-streak-stats#628]
**Description**
I created a repository which was cloned from another repository & pushed the initial project.

In my Github contribution it shows my streak is intact from 6th dec 23.
<img width="369" alt="Screenshot 2023-12-24 at 9 58 56 AM" src="https://github.com/DenverCoder1/github-readme-streak-stats/assets/63944420/614aa5bf-0a60-47d9-aa33-f914d358332e">

But in github-readme-streak-stats it says I missed on 22nd dec 23
<img width="527" alt="Screenshot 2023-12-24 at 9 59 09 AM" src="https://github.com/DenverCoder1/github-readme-streak-stats/assets/63944420/da66c719-3efe-4bdb-9aab-548488cb1a43">

**Comment by DenverCoder1** [comment]
There's more info in the faq

https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/faq.md#why-doesnt-my-streak-stats-match-my-contribution-graph

https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/faq.md#what-is-considered-a-contribution

It may be a timezone-related issue in which case, you can manually create backdated commits if the streak matters enough.

**Comment by AkshayAshokCode** [comment]
Thanks Johan,
The streak was important to me.
Thank you for this amazing Repo.
