### ISSUE TITLE
Github Stats not displaying

### ISSUE THREAD

**Issue by kyle-mcr** [DenverCoder1/github-readme-streak-stats#631]
**Describe the bug**
The github streak Was showing properly for the past week and today it is now only showing the img alt: `alt="GitHub Streak"` and not showing any of the stats.
 
**To Reproduce**

1. Go to ['streak-stats.demolab'](https://streak-stats.demolab.com/demo/)
2. Generate a html block for your stats
3. Paste html block inside GH read me
4. See error inside your github read me

**Expected behavior**
The github stats to show as they do in the preview/what was showing in the past

**Screenshots**
![January,09,2024,10’43’32AM](https://github.com/DenverCoder1/github-readme-streak-stats/assets/53325780/9d7f6487-7ee8-44e7-af19-4d85ab2e911a)

**Desktop (MacBook Pro M1 2021):**

- OS: Mac OS 14.1.2
- Chrome
- Version 120.0.6099.129 (Official Build) (arm64)

**Additional context**
Was working yesterday and the past few days

**Comment by joshlawlor** [comment]
I am also experiencing the same issue but on Windows

**Comment by luckymurari** [comment]
This seems to be broken for everyone as the server is down.

https://github.com/DenverCoder1/DenverCoder1 also doesn't display

**Comment by tidalu** [comment]
the same issue is on windows, ```Error Fetching Resource```

**Comment by FleetAdmiralJakob** [comment]
Same issue. The service seems to be down. @DenverCoder1 has the same problem on his README.

**Comment by Sivakajan-tech** [comment]
For me also!!!

**Comment by DenverCoder1** [comment]
https://github.com/DenverCoder1/github-readme-streak-stats/issues/616#issuecomment-1787834794

**Comment by LandryHouston** [comment]
Aw man... I'm glad I'm not the only one though!
