### ISSUE TITLE
Failed to retrieve contributions

### ISSUE THREAD

**Issue by lombardi-g** [DenverCoder1/github-readme-streak-stats#635]
I hosted the project locally following the instructions on the readme file.
Since 2024 started i noticed the card with fetch errors such as the image below:
![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/127768914/0a10c8ff-e36d-4f4a-8cc1-e7356d142172)

This is the url
https://github-readme-streak-stats-lombardi-gs-projects.vercel.app/?user=lombardi-g&theme=soft-green&card_width=390
and my own deploy
https://github.com/lombardi-g/github-readme-streak-stats

- OS: Windows 11
- Browser Google Chrome
- Version 9.6.15

**Comment by DenverCoder1** [comment]
Have you made sure you have a valid token in the environment varialbles?

If you're using your own deployment, this is probably the first GitHub API issue to check.

**Comment by xHyroM** [comment]
Happens also for me, didn't happen like 5 days ago.

**Comment by ibalpinar** [comment]
I'm experiencing the issue as well, and I can even say that the image has not been created for 3 days. You can see below
![Screenshot 2024-01-12 at 2 07 21 AM](https://github.com/DenverCoder1/github-readme-streak-stats/assets/1355079/cde65a37-da49-41bc-bbbd-ed6796f5bc5a)

**Comment by ccfontes** [comment]
Dropping a me too.
Was working last week.

**Comment by exotics1337** [comment]
Experiencing the same Issue currently, Image is not being loaded

**Comment by lombardi-g** [comment]
> Have you made sure you have a valid token in the environment varialbles?
> 
> If you're using your own deployment, this is probably the first GitHub API issue to check.

I checked the token, in fact it was expired on Jan 1, 2024. I regenerated it and updated the token on my Vercel deploy, but still meet the same API issue. Any other troubleshooting ideas?

![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/127768914/ff82032a-2104-4890-a140-1e56197d269b)

**Comment by sahanajprakash** [comment]
Facing the same issue

**Comment by sahanajprakash** [comment]
@lombardi-g i found this response on another issue (616)
https://github.com/DenverCoder1/github-readme-streak-stats/issues/616#issuecomment-1787834794
Maybe this can help
Linking the solution to deploy on your own here
https://github.com/DenverCoder1/github-readme-streak-stats?tab=readme-ov-file#-deploying-it-on-your-own

**Comment by ccfontes** [comment]
Hmm, also maybe I need to stop refreshing my github home so much just to see delightful stats.
I'm starting today.

**Comment by DenverCoder1** [comment]
> I checked the token, in fact it was expired on Jan 1, 2024. I regenerated it and updated the token on my Vercel deploy, but still meet the same API issue. Any other troubleshooting ideas?

After changing the token, you may need to trigger a new deployment to get it to update

**Comment by xHyroM** [comment]
> @lombardi-g i found this response on another issue (616) [#616 (comment)](https://github.com/DenverCoder1/github-readme-streak-stats/issues/616#issuecomment-1787834794) Maybe this can help Linking the solution to deploy on your own here https://github.com/DenverCoder1/github-readme-streak-stats?tab=readme-ov-file#-deploying-it-on-your-own

That's probably it, thanks. I'll self host it 😀😃

**Comment by lombardi-g** [comment]
> > I checked the token, in fact it was expired on Jan 1, 2024. I regenerated it and updated the token on my Vercel deploy, but still meet the same API issue. Any other troubleshooting ideas?
> 
> After changing the token, you may need to trigger a new deployment to get it to update

This solved it! I commited a minor change to the README.md to trigger a new deploy and it's back to normal.
