### ISSUE TITLE
Make homepage redirect to demo site

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-streak-stats#64]
When a user visits the "homepage" of Streak Stats (https://github-readme-streak-stats.herokuapp.com/), they simply see a card saying the user cannot be found:

![image](https://user-images.githubusercontent.com/20955511/114065579-80a01c80-98a3-11eb-8235-0968b9d197ab.png)

It would probably be more helpful to redirect them to a page with more information such as the [Demo Site](https://github-readme-streak-stats.herokuapp.com/demo) which explains the purpose of the tool and has links to the GitHub repo.

**Comment by himanshu007-creator** [comment]
I would like to work on this issue, please guide me further.

**Comment by DenverCoder1** [comment]
Hi @himanshu007-creator, that would be great!

Basically what needs to be done is a simple change in [index.php](https://github.com/DenverCoder1/github-readme-streak-stats/blob/1d94c623a132803d4b9a010efb785a43902f728b/src/index.php) that will check if the "user" property of `$_REQUEST` [is set](https://www.php.net/manual/en/function.isset.php) and if it is not, redirect to the demo site which can be done with a [Location header](https://www.php.net/manual/en/function.header.php).

Let me know if you have any questions. :)

**Comment by himanshu007-creator** [comment]
> Hi @himanshu007-creator, that would be great!
> 
> Basically what needs to be done is a simple change in [index.php](https://github.com/DenverCoder1/github-readme-streak-stats/blob/1d94c623a132803d4b9a010efb785a43902f728b/src/index.php) that will check if the "user" property of `$_REQUEST` [is set](https://www.php.net/manual/en/function.isset.php) and if it is not, redirect to the demo site which can be done with a [Location header](https://www.php.net/manual/en/function.header.php).
> 
> Let me know if you have any questions. :)

Okay I will work in it today
