### ISSUE TITLE
Already deployed on vercel but not working Streak-stats

### ISSUE THREAD

**Issue by Syfer0** [DenverCoder1/github-readme-streak-stats#641]
https://streak-stats-jade.vercel.app/demo/ 

but still not working on my Readme file Can anyone help?

**Comment by FleetAdmiralJakob** [comment]
Same issue.
![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/77451351/75c2d572-339f-493e-923e-f07f322f66a0)

**Comment by Syfer0** [comment]
> Same issue. ![image](https://private-user-images.githubusercontent.com/77451351/299388874-75c2d572-339f-493e-923e-f07f322f66a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNjA3OTgsIm5iZiI6MTcwNjE2MDQ5OCwicGF0aCI6Ii83NzQ1MTM1MS8yOTkzODg4NzQtNzVjMmQ1NzItMzM5Zi00OTNlLTkyM2UtZjA3ZjMyMmY2NmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA1MjgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZGVlMmVkOTYwNTA3YjViYjY0OTJiYWQ0ZjYzYmZhNzg4NDMxNzhhNTdkYWE5YzNiZjJhNDA3MjJmY2UxZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.doSlQLw2awxeg8zIuZI5kID3YuUu-cesWyY8cXbDKyk)

I don't have that issue I am having an issue it's not rendering in my readme.md file

**Comment by FleetAdmiralJakob** [comment]
I went to your website and when I clicked on the link and tried to access the stats of a user I got the error

**Comment by DimaKoz** [comment]
https://github.com/DimaKoz/dimakoz/blob/main/README.md?plain=1

I got the same issue - an image doesn't render inside my readme.md file
for  `[![GitHub Streak](https://streak-stats.demolab.com/?user=dimakoz)](https://git.io/streak-stats)`
although [link https://streak-stats.demolab.com/?user=dimakoz](https://streak-stats.demolab.com/?user=dimakoz) works

**Comment by FleetAdmiralJakob** [comment]
How did you get it working?

**Comment by DimaKoz** [comment]
> How did you get it working?

I didn't do anything, I thought you fixed it. :)

**Comment by DaydreamsDev** [comment]
> How did you get it working?

The link is not self hosted on Vercel
[](https://streak-stats.demolab.com/?user=dimakoz)

**Comment by Syfer0** [comment]
https://streak-stats-jade.vercel.app/demo/
Here is my Deploy link  But 

[![GitHub Streak](https://streak-stats-jade.vercel.app?user=Syfer0)](https://git.io/streak-stats)


<a href="https://git.io/streak-stats"><img src="https://streak-stats-jade.vercel.app?user=Syfer0" alt="GitHub Streak" /></a>

**Comment by DaydreamsDev** [comment]
I have the same issue
Link to my card
[https://github-readme-streak-daydreamsdeveloper.vercel.app/?user=DaydreamsDev](https://github-readme-streak-daydreamsdeveloper.vercel.app/?user=DaydreamsDev)
Link to my deployment
[https://github-readme-streak-daydreamsdeveloper.vercel.app/demo/](https://github-readme-streak-daydreamsdeveloper.vercel.app/demo/)

**Comment by DenverCoder1** [comment]
It's working for me without any changes but should be fixed by #646 - Update vercel php to 0.6.1
