### ISSUE TITLE
Bug(Vercel): Fatal error: Uncaught Error: Call to undefined function curl_init()

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [DenverCoder1/github-readme-streak-stats#642]
**Describe the bug**
https://[github-readme-streak-stats-zeta-red.vercel.app/?user=FleetAdmiralJakob](https://github-readme-streak-stats-zeta-red.vercel.app/?user=FleetAdmiralJakob)

**To Reproduce**
Got to the forked Website:

Website: https://github-readme-streak-stats-zeta-red.vercel.app/?user=FleetAdmiralJakob
GH: https://github.com/The-Creative-Programming-Group/github-readme-streak-stats/tree/vercel

And see the error

**Expected behavior**
It shows me my streak-stats

**Desktop (please complete the following information):**

I opened the Website in Edge

**Additional context**
I forked it and used the vercel branch as the code for the vercel website.

**Comment by FleetAdmiralJakob** [comment]
It seems that this is a general error since other apps: https://streak-stats-jade.vercel.app?user=FleetAdmiralJakob from this issue #641 have the same error.

**Comment by ironashram** [comment]
fyi the fix is in vercel-php 0.6.1, found it [here](https://github.com/vercel-community/php/issues/512)
just tested on my fork and it works fine after upgrading

**Comment by DenverCoder1** [comment]
#646
