### ISSUE TITLE
Vercel deployed version no longer working properly

### ISSUE THREAD

**Issue by joshlawlor** [DenverCoder1/github-readme-streak-stats#654]
**Describe the bug**
My personal access token expired, so I went in and created a new one. That is when this issue began. My vercel says the initial project is still deployed and build ran fine. But I am unable to access the streaks.

I get the following error when attempting to access 'https://github-readme-streak-stats-blue-one.vercel.app/?user=joshlawlor':

`Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/task/user/api/stats.php:234 Stack trace: #0 /var/task/user/api/stats.php(49): getGraphQLCurlHandle('query {\n ...', 'ghp_ejVPeNdAomW...') #1 /var/task/user/api/stats.php(126): executeContributionGraphRequests('joshlawlor', Array) #2 /var/task/user/api/index.php(38): getContributionGraphs('joshlawlor', NULL) #3 {main} thrown in /var/task/user/api/stats.php on line 234`

**To Reproduce**

1. Go to 'https://github-readme-streak-stats-blue-one.vercel.app/?user=joshlawlor'
2. See error

**Expected behavior**
1. Go to 'https://github-readme-streak-stats-blue-one.vercel.app/?user=joshlawlor'
2. See stats

**Screenshots**
![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/101484054/90712282-cab1-420c-9418-5a07cf42cbd0)

**Desktop (please complete the following information):**

- OS: Windows 10
- Chrome
- Running off vercel-php version '0.6.0'

**Comment by tribhuwan-kumar** [comment]
I'm also getting the same error:

```Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/task/user/api/stats.php:234 Stack trace: #0 /var/task/user/api/stats.php(49): getGraphQLCurlHandle('query {\n ...', 'ghp_CQrZabakULW...') #1 /var/task/user/api/stats.php(126): executeContributionGraphRequests('tribhuwan-kumar', Array) #2 /var/task/user/api/index.php(37): getContributionGraphs('tribhuwan-kumar', NULL) #3 {main} thrown in /var/task/user/api/stats.php on line 234```

Is there any solution you got ?

**Comment by DenverCoder1** [comment]
Try using vercel-php@0.6.1 in vercel.json

**Comment by joshlawlor** [comment]
> Try using `vercel-php@0.6.1` in vercel.json

This worked
