### ISSUE TITLE
Unable to deploy on Vercel

### ISSUE THREAD

**Issue by noahnightmare** [DenverCoder1/github-readme-streak-stats#666]
**Describe the bug**
Project unable to be deployed on Vercel, with error below.

**To Reproduce**
Attempt to deploy it on vercel.

php: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
--
17:30:56.046 | Error: Exited with 127
17:30:56.046 | at ChildProcess.<anonymous> (/vercel/path0/.vercel/builders/node_modules/vercel-php/dist/utils.js:182:24)
17:30:56.046 | at ChildProcess.emit (node:events:518:28)
17:30:56.046 | at ChildProcess.emit (node:domain:488:12)
17:30:56.046 | at ChildProcess._handle.onexit (node:internal/child_process:294:12)
17:30:56.088 | Error: Command "vercel build" exited with 1
17:30:56.171 | Command "vercel build" exited with 1

I've tried multiple times using multiple different repos and tokens however I keep getting the same problem. Am I missing something?

**Comment by fivaz** [comment]
same

**Comment by ibrahim11elian** [comment]
same

**Comment by mrdandelion6** [comment]
same

**Comment by Mquiuqui** [comment]
same

**Comment by Machine-Maker** [comment]
In the vercel project settings, change the node version to 18.x from the default of 20.x

**Comment by DenverCoder1** [comment]
Should be fixed for future deployments
