### ISSUE TITLE
Wrong Date/Zero Streak Bug

### ISSUE THREAD

**Issue by EJ-Lan** [DenverCoder1/github-readme-streak-stats#667]
**Describe the bug**
* I have a streak of contributions that should still be going, I have not stopped committing today on the 4th of April but it says I have a 0 streak and that my streak ended on the 3rd of April. I have committed already for today 4th of April.
* I also have noticed that the "current streak" says April 5th rather than the current date April 4th

**To Reproduce**

1. Go to Github Profile
2. Click on Profile readme
3. Scroll down to Section where streak stats card is

**Expected behavior**
There should be a streak that is still going.

**Screenshots**
![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/78132918/135aa03b-0a89-4bbf-a663-93174ed84678)
![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/78132918/4ce7cd85-4685-45be-96ef-9637ebcb5197)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Firefox
- Version 125.0b8 (64-bit)

**Comment by kunle009** [comment]
Having similar issues too streak added plus one day and current streak reset to 0 despite committing yesterday.

**Comment by EJ-Lan** [comment]
Seems like the issue has been fixed!
