### ISSUE TITLE
🐛 Toggle Theme Button on top of Heading on mobile view

### ISSUE THREAD

**Issue by vikasganiga05** [DenverCoder1/github-readme-streak-stats#67]
**Describe the bug**
The toggle theme button on mobile view overlaps the heading element. Which is not good for the user experience.

**To Reproduce**
> On Desktop / Laptop
1. Go to https://github-readme-streak-stats.herokuapp.com/demo
2. Right-click on the page and select `inspect`.
3. Then Click on the `Toggle device toolbar` on the top-left of DevTools.
4. Now change the viewport to mobile view.
5. See the bug - toggle theme button that overlaps the heading element.

> On Smart-Phone
1. Go to https://github-readme-streak-stats.herokuapp.com/demo
2. See the bug - toggle theme button that overlaps the heading element.

**Expected behavior**
Option 1: Set default theme to `Dark Theme`. Then remove the toggle theme button on mobile view.
Option 2: Place the toggle theme button in such a place that doesn't affect other elements on the page.

**Screenshots**

![download](https://user-images.githubusercontent.com/74750414/114254827-7418e280-99cf-11eb-957f-dec991578129.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - OS: Android 11.0 with One UI 3.0
 - Browser: Chrome
 - Version: 89.0.4389.105

**Additional context**
I checked in almost all smartphone simulators and phones. I found the same bug.

**Comment by DenverCoder1** [comment]
I think the second option is better since people may want to see how it will look on GitHub's light mode and dark mode.

Maybe we could have a toggle at the bottom of the page that appears on small screens and have the corner button only appear on large screens.

**Comment by vikasganiga05** [comment]
> I think the second option is better since people may want to see how it will look on GitHub's light mode and dark mode.
> 
> Maybe we could have a toggle at the bottom of the page that appears on small screens and have the corner button only appear on large screens.

Your right sir, I came up with this idea. Positioned the toggle button on the bottom right corner of the page then changed the background color of the toggle button to blue.

![mobile](https://user-images.githubusercontent.com/74750414/114307533-af193400-9afd-11eb-8451-d9374b20430b.gif)

**Comment by DenverCoder1** [comment]
Looks good, do you want to make a PR to fix it?

**Comment by vikasganiga05** [comment]
> Looks good, do you want to make a PR to fix it?

Yeah! I will fix it.
