### ISSUE TITLE
Vercel Deployment fails due to error loading php shared libraries

### ISSUE THREAD

**Issue by madaley1** [DenverCoder1/github-readme-streak-stats#679]
**Describe the bug**
When deploying to vercel, after creating the repository and adding the token the build exits with an error

Logs: 
```
Running build in Washington, D.C., USA (East) – iad1
--
09:05:53.768 | Cloning github.com/madaley1/github-readme-streak-stats (Branch: main, Commit: e7a7629)
09:05:54.298 | Previous build cache not available
09:05:54.518 | Cloning completed: 746.5ms
09:05:54.571 | Found .vercelignore
09:05:54.578 | Removed 1 ignored files defined in .vercelignore
09:05:55.019 | Running "vercel build"
09:05:55.984 | Vercel CLI 34.1.10
09:05:56.386 | > Installing Builder: vercel-php@0.6.1
09:06:01.188 | 🐘 Downloading user files
09:06:01.188 | 🐘 Downloading PHP runtime files
09:06:01.192 | 🐘 Installing Composer dependencies [START]
09:06:01.455 | php: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
09:06:01.469 | Error: Exited with 127
09:06:01.470 | at ChildProcess.<anonymous> (/vercel/path0/.vercel/builders/node_modules/vercel-php/dist/utils.js:182:24)
09:06:01.470 | at ChildProcess.emit (node:events:518:28)
09:06:01.470 | at ChildProcess.emit (node:domain:488:12)
09:06:01.471 | at ChildProcess._handle.onexit (node:internal/child_process:294:12)
09:06:01.493 | Error: Command "vercel build" exited with 1
09:06:01.577 | Command "vercel build" exited with 1

```

**To Reproduce**
Follow the steps provided for Vercel in the `Deploying it on your own` section of the Readme

**Expected behavior**
It should deploy and be able to be accessed via the vercel deployment url

**Screenshots**
![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/61160473/57f62efa-58e7-454f-b174-f0fec72f2431)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Arc (Based on Chromium version 124.0.6367.60 (Official Build) (64-bit))

**Additional context**
I'm not sure if there are any steps that I missed, but I believe I did the process as outlined in the tutorial a couple times and it was the same result both times.

**Comment by Machine-Maker** [comment]
In the vercel project settings, change the node version to 18.x from the default of 20.x

**Comment by madaley1** [comment]
This worked, thanks!
