### ISSUE TITLE
Streak Templete not showing 

### ISSUE THREAD

**Issue by xcriminal1** [DenverCoder1/github-readme-streak-stats#683]
![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/75941853/82ba5ec4-5128-4fd7-b403-3410d51e564e)

**Comment by itzmidinesh** [comment]
Yes, streak is not showing up for me too.

**Comment by harsh8088** [comment]
**Mine is showing this Error!**

<img width="1133" alt="Screenshot 2024-05-20 at 12 02 09 PM" src="https://github.com/DenverCoder1/github-readme-streak-stats/assets/7496696/30cc32c7-4273-4202-97ac-6b09cf8351cb">

**Comment by Mcorduk** [comment]
Same here.

**Comment by Zerabalus** [comment]
omg same

**Comment by djpaul-dev** [comment]
same ;-;

**Comment by parth-007** [comment]
Same for me. please resolve

**Comment by joao-alvar** [comment]
Hey, are you using &hide_border=true? This seems to be the problem.

**Comment by henryonsoftware** [comment]
Same here

**Comment by lmisea** [comment]
Same :(

**Comment by djpaul-dev** [comment]
Guys, check this issue from a while ago. [Streak markdown is not shown on GitHub profile #616](https://github.com/DenverCoder1/github-readme-streak-stats/issues/616). 

**Self-hosting solved my problem!**

This is what the repo owner (aka. Jonah) said.

> When there is a lot of traffic to the Heroku server, the GitHub API seems to stop sending back content and the responses become very slow. If it takes too long to load, GitHub will just show a broken image instead of waiting. GitHub also caches responses on their server, so even if the speed gets back to normal, it could still show as broken on GitHub for a particular image URL for up to a few hours.
> 
> To avoid this issue, I recommend self-hosting the project. There are steps in the readme, I recently added a new method for deploying with Vercel entirely online. It's free and shouldn't take more than a couple minutes to set up.
> 
> It should also start working on its own, but there isn't much I can do to prevent it from going down in the future while hosting for over 100,000 people for free*, so self-hosting is still an option to get it to stay up more reliably.
> 
> Scaling up to use multiple processes seems to resolve the issue but this costs about $50/month and since the project does not make any money for me and I'm not making that much from sponsorships I'd rather keep it at the lowest pricing tier. If I get at least $25/month in sponsorships, I'd keep the server scaled up.

I think it was generous of Jonah to make this project open-source and have the hosting server scaled up for us as long as he could. I had no clue he was paying that much per month despite this project not generating any revenue. 

Jonah was also generous enough to provide some instructions on how we could host this on Vercel and Heroku. Hosting on Vercel is free btw! Check out the self-hosting instructions on his repo, under the section "[Deploying it on your own](https://github.com/DenverCoder1/github-readme-streak-stats?tab=readme-ov-file#-deploying-it-on-your-own)". Here's a video on self-hosting this by Jonah himset! [How To Self-Host GitHub Readme Streak Stats on Vercel
](https://youtu.be/maoXtlb8t44?si=Lgglf0dSzY2Zumeu)

**Comment by denivic** [comment]
That was indeed very generous of Jonah. Thank you!

And thanks @djpaul-dev for the self-host links.
