### ISSUE TITLE
When used with hide_border=true it shows the error Failed to retrieve contributions. This is likely a GitHub API issue

### ISSUE THREAD

**Issue by joao-alvar** [DenverCoder1/github-readme-streak-stats#684]
Browser - Vivaldi

Tested three Markdowns apps to see if the issue persisted - stackedit.io, markdownlivepreview, dillinger.io.

Only when I add &hide_border=true the bug appears

**Comment by DenverCoder1** [comment]
When there is a lot of traffic to the Heroku server, the GitHub API seems to stop sending back content and the responses become very slow.

To avoid this issue, I recommend self-hosting the project. There are steps in the readme, I recently added a new method for deploying with Vercel entirely online. It's free and shouldn't take more than a couple minutes to set up.

It should also start working on its own, but there isn't much I can do to prevent it from going down in the future, so self-hosting is still an option to get it to stay up more reliably.

Related: #592, #601, etc

**Comment by joao-alvar** [comment]
When I tried to helf-host with Vercel it showed an error. Here is the screen shot of the error
![2024-05-20 17 09 05 vercel com 57b9df50173b](https://github.com/DenverCoder1/github-readme-streak-stats/assets/74555541/e2d6e91a-ef5e-4f40-a517-b73353361012)

**Comment by DenverCoder1** [comment]
https://github.com/DenverCoder1/github-readme-streak-stats/issues/679#issuecomment-2119706622

Try this maybe? 

> In the vercel project settings, change the node version to 18.x from the default of 20.x

**Comment by joao-alvar** [comment]
This works. Thanks!
