### ISSUE TITLE
Dynamic theme change (Dark or Light)

### ISSUE THREAD

**Issue by lucasdevtec** [DenverCoder1/github-readme-streak-stats#685]
Dynamic theme change (Dark or Light)

Example:  (There are two elements here!)

[![GitHub stats-Dark](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&theme=dark#gh-dark-mode-only)](https://github.com/anuraghazra/github-readme-stats#gh-dark-mode-only)

[![GitHub stats-Light](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&theme=default#gh-light-mode-only)](https://github.com/anuraghazra/github-readme-stats#gh-light-mode-only)

```

[![GitHub stats-Dark](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&theme=dark#gh-dark-mode-only)](https://github.com/anuraghazra/github-readme-stats#gh-dark-mode-only)

[![GitHub stats-Light](https://github-readme-stats.vercel.app/api?username=anuraghazra&show_icons=true&theme=default#gh-light-mode-only)](https://github.com/anuraghazra/github-readme-stats#gh-light-mode-only)

```

It would be really cool to have this functionality!

PS: If it exists, I'm sorry but I didn't find it in the documentation.

Thanks!

**Comment by DenverCoder1** [comment]
The scheme context feature is part of GitHub and not specific to GitHub Stats, so it works for any images you want including Streak Stats.

I have documentation here in the FAQ on the way that is currently recommended:

https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/faq.md#how-do-i-make-different-images-for-dark-mode-and-light-mode

**Comment by lucasdevtec** [comment]
OK I understand! Sorry for the lack of knowledge!

Thank you for your help! <3
