### ISSUE TITLE
Issue in the stats generation and demo page

### ISSUE THREAD

**Issue by MiguelALopez** [DenverCoder1/github-readme-streak-stats#697]
# Issue Description

## Demo Page Instability
The demo page is currently unstable. Sometimes it functions as expected, but at other times, it fails to load properly.

![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/8294982/414c446b-1843-4fc8-a398-f8562ef121fe)

## Stats Image Generation Error
Additionally, the stats image is not being generated, but I'm not sure if it's really an error of Github or an error in the deployment of the app

![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/8294982/c893d4af-c800-418f-92f4-44b6c534331b)

Lastly it's a great project, thank you 💪💯

**Comment by itsmenewbie03** [comment]
Also Experiencing this issue

**Comment by JPDengler** [comment]
Same here, I assume host is down or something?

**Comment by JPDengler** [comment]
> it's back up
![Screenshot_20240701_205429_Chrome](https://github.com/DenverCoder1/github-readme-streak-stats/assets/130941901/dbf86e64-2228-4695-b02d-c4c86615dcc0)

**Comment by MiguelALopez** [comment]
It seems to be working now
