### ISSUE TITLE
Bug `excluded_days` when using it inside `<picture>`

### ISSUE THREAD

**Issue by scrodrig** [DenverCoder1/github-readme-streak-stats#701]
**Describe the bug**
I want to use the streak inside a `picture` tag for being able to change colors properly based on color system preference, but for some reason is excluding the day from the query param

**To Reproduce**

```html
<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://github-readme-streak-stats.herokuapp.com/?user=scrodrig&theme=darcula&card_width=600px&exclude_days=Sat,Sun" />
    <source media="(prefers-color-scheme: light)" srcset="https://github-readme-streak-stats.herokuapp.com/?user=scrodrig&theme=buefy&card_width=600px&exclude_days=Sat,Sun" />
    <img alt="scrodrig-stats2" src="https://github-readme-streak-stats.herokuapp.com/?user=scrodrig&theme=buefy&card_width=600px&exclude_days=Sat,Sun" />
</picture>
```

The first one with 7 days is the one from `picture`, the second one is written normally 

``` html
<p align="center">
    <img alt="scrodrig-stats2" src="https://github-readme-streak-stats.herokuapp.com/?user=scrodrig&theme=buefy&card_width=600px&exclude_days=Sat,Sun" />
</p>
```

**Expected behavior**
See the same number of days. You might notice when using inside `<picture>` is not taking what is next to `,`

**Screenshots**
![image](https://github.com/user-attachments/assets/2ba81d77-28b6-4ac8-8991-d6e9ed40b53e)

**Desktop (please complete the following information):**

- Browser Brave
- Version 1.67.123

**Additional context**
Seems to be only with that specific query param (related to `,`), I also have some issues placing the theme as the last parameter but I couldn't reproduce it properly.

**Comment by scrodrig** [comment]
Reading a bit of the documentation, this is probably more related to the `beta` state of `<picture>` tag in `markdown (Not sure)

**Comment by DenverCoder1** [comment]
Thanks for reporting! 

It appears to me that it's on GitHub's end to fix, but you could try replacing the `,` with the URI encoding `%2C` and see if that helps.

**Comment by scrodrig** [comment]
Yeah, seem it is more related to github end, however using `%2C` worked,
Thanks a lot
