### ISSUE TITLE
Total Contributions not correct

### ISSUE THREAD

**Issue by K7413dS433d** [DenverCoder1/github-readme-streak-stats#704]
**Describe the bug**
Not get the Total Contributions do not correct

**Comment by DenverCoder1** [comment]
It matches exactly what GitHub's API returns, so there is nothing else to do

134+139+2+1 = 276

![image](https://github.com/user-attachments/assets/2ad9fd5b-82bd-4a28-9b9e-c5cff1d173a0)
![image](https://github.com/user-attachments/assets/4a0243bc-fa4e-41e9-811e-2ffc57b49b5e)
![image](https://github.com/user-attachments/assets/20b29f0f-52d6-4608-9ea4-d67a26131920)
![image](https://github.com/user-attachments/assets/f90eec09-9e2b-45f8-8c1e-d8b36ea8ce94)

![image](https://github.com/user-attachments/assets/c7c8b368-1110-4265-8104-42660d0e6991)
