### ISSUE TITLE
Not updating if not on main branch

### ISSUE THREAD

**Issue by KColagiovanni** [DenverCoder1/github-readme-streak-stats#712]
**Description**

Thank you for the awesome streak stat. My question is: I am wondering if the streak is not supposed to get updated when working on a branch other than "main"? I haven't tested it on multiple repos, but my 47 day streak was broken when I started working on a branch off the main branch. Is this expected? Thanks again.

**Comment by KColagiovanni** [comment]
Noticed after further investigation that there were no contributions on the contribution heat map on the two days that caused my streak to end, even though my repo showed "last updated" as "x minutes ago" on each day (I usually check to make sure the update was pushed).

**Comment by DenverCoder1** [comment]
Yes, for more info see https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile

Specifically:

> Commits will appear on your contributions graph if they meet all of the following conditions:
> 
> * The email address used for the commits is associated with your account on GitHub.
> * The commits were made in a standalone repository, not a fork.
> * The commits were made:
>   * **In the repository's default branch**
>   * In the `gh-pages` branch (for repositories with project sites)

**Comment by KColagiovanni** [comment]
Thank you for the info, I appreciate it!
