### ISSUE TITLE
Feature Suggestion: Adaptive Theme Support for Profile/Steak Stats

### ISSUE THREAD

**Issue by PrabhukumarSivamoorthy** [DenverCoder1/github-readme-streak-stats#720]
**Feature request Summary:**
I have noticed that the profile appearance can seem odd when using specific themes. While the visual consistency aligns with my own theme settings, it may appear disjointed for recruiters or followers who have different preferences.

For instance, my GitHub profile theme is set to dark, and I have chosen the GitHub Dark theme for my statistics. However, when a follower or recruiter views my profile with a light theme, the overall appearance can look mismatched and unappealing.

Although a majority of programmers tend to use dark themes, many individuals prefer their own customized settings. It would greatly enhance user experience if our statistics could adapt dynamically to the theme preferences of viewers.

**Comment by DenverCoder1** [comment]
Some of the themes are transparent (ones ending in -duo) and show the background of the user's theme.

There are also instructions towards the end of the FAQ on how to use different themes for light mode and dark mode

https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs%2Ffaq.md

**Comment by PrabhukumarSivamoorthy** [comment]
Thanks @DenverCoder1 for the info. I was able to update the profile. The above information is helpful. 
Hence closing this issue.
