### ISSUE TITLE
Wrong Total Contributions Count

### ISSUE THREAD

**Issue by jgphilpott** [DenverCoder1/github-readme-streak-stats#725]
**Describe the Bug**

For users with a large number of contributions, such as those with numbers in the millions ([Linus Torvalds](https://github.com/torvalds) for example) the stats for Total Contributions seem wrong, see below ... 

<img src="https://streak-stats.demolab.com/?user=torvalds">

Is that supposed to be 32 million, it's got to be more than 32 thousand! Is it only showing the first 5 digits or something? ...

**To Reproduce**

 - Look at the streak-stats for any world famous developer that has contributions in the hundreds of thousands or millions.

**Expected behavior**

Maybe after 100,000 it starts to use abbreviations like 100K until 999k then switch to 1M until 999M then 1B ... I don't think the numbers go that high ... it couldn't hurt to future proof the app though! 

**Screenshots**

<img src="https://streak-stats.demolab.com/?user=torvalds">

**Desktop (please complete the following information):**

**N/A**

**Smartphone (please complete the following information):**

**N/A**

**Additional context**

**N/A**

**Comment by DenverCoder1** [comment]
If you look at the contribution graph on his profile it adds up.

Only commits since the creation of the GitHub account are counted. Commits that were migrated from another platform and were made before the account creation are not included.

**Comment by jgphilpott** [comment]
Okay, but take a look at the profile for [mrdoob](https://github.com/mrdoob), the creator of three.js ... his stats card shows 2154K (aka 2.1M) commits but if I look at his streak-stats Total Contributions its only showing 23.6k? ... shouldn't is be at least as much as his commits or even more? 

<img src="https://github-readme-stats.vercel.app/api?username=mrdoob&count_private=true&show_icons=true&include_all_commits=true&hide_border=true&hide_title=true">

<img src="https://github-readme-streak-stats.herokuapp.com/?user=mrdoob">

OR

[Evan You](https://github.com/yyx990803) the creator or Vue.js, this is this stats card

<img src="https://github-readme-stats.vercel.app/api?username=yyx990803&count_private=true&show_icons=true&include_all_commits=true&hide_border=true&hide_title=true">

but this is his streak-stats Total Contributions

<img src="https://github-readme-streak-stats.herokuapp.com/?user=yyx990803">

... do you have any example of streak-stats Total Contributions of 100k or more? Someone should have that many or will one day soon, here are [GitHub's most famous people](https://github.com/search?o=desc&q=followers%3A%3E%3D1000&ref=searchresults&s=followers&type=Users).

**Comment by DenverCoder1** [comment]
Commits are not necessarily always considered contributions by GitHub. Commits outside the default branch or in forks don't count. Also commits to repositories that the user has not interacted with on GitHub (maybe unrelated commits made with the user's email address?)

More info on that: 
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile

The contributions are coming directly from the GitHub API, so it should be consistent with the way GitHub counts it.

Checking this project, they get similar counts: https://github-contributions.vercel.app/

**Comment by jgphilpott** [comment]
Okay but is the app configured to use short form for the total contribution count after a certain threshold? What will it do when someones contribution count reaches 100,000 or 1,000,000? Does it become 100k and 1M (possibly with 1 decimal point) or does it show the raw number? Displaying 6 digits could be okay but with 7 it will start looking squished! We should be prepared for this scenario and have tests for it!

... maybe I should change the name of this ticket to something like 'Use short form for Total Contributions that have large igniters' and make it a feature request rather than a bug? It could even be an option like `?use_short_form=true`.

**Comment by jgphilpott** [comment]
It could even kick in as low as 1,000 and use 1 decimal point.

**Comment by DenverCoder1** [comment]
Sounds like a good plan. I wouldn't consider it urgent right now, but I'd be happy to add the feature or have someone contribute it. 

Something similar to this algorithm could be used.

```php
// short numbers from https://stackoverflow.com/a/52490452/11608064
function shortNumber($num)
{
    $units = ['', 'K', 'M', 'B', 'T'];
    for ($i = 0; $num >= 1000; $i++) {
        $num /= 1000;
    }
    return round($num, 1) . $units[$i];
}
```

I also think it makes sense to make it a query flag so if people like it the way it is with the full number, they can keep it that way, but I think it's fine to make the default "true".

**Comment by jgphilpott** [comment]
Okay great! I will actually create a new ticket rather than renaming this one though so that it has a clear history.
