### ISSUE TITLE
Border false breaking TokyoNight theme

### ISSUE THREAD

**Issue by noxidsoft** [DenverCoder1/github-readme-streak-stats#747]
**Describe the bug**
Reverts to link for streak git address

**To Reproduce**

1. set border to `true`
2. ```[![GitHub Streak](https://streak-stats.demolab.com?user=Noxidsoft&theme=tokyonight&hide_border=true)](https://git.io/streak-stats)```

**Expected behavior**
Should render as it did before

**Screenshots**
![image](https://github.com/user-attachments/assets/8a35e978-9a36-4e05-b3d9-bc06d4cf0161)

**Desktop (please complete the following information):**

- OS: Ubuntu 24.04 LTS (gnome in dark mode)
- Browser Firefox
- Version 133.0.3 64-bit

**Smartphone (please complete the following information):**

- n/a

**Additional context**
Just started happening a few days ago, was working just fine with a self-hosted Heroku app, when I switched to demolab version, same thing? For now I'm going to remove the border.

**Comment by noxidsoft** [comment]
Only this seems to work. If I add any other parameters it fails:
<a href="https://git.io/streak-stats"><img src="https://streak-stats.demolab.com?user=Noxidsoft&theme=tokyonight" alt="GitHub Streak" /></a>

**Comment by noxidsoft** [comment]
What I have tried:
`


<a href="https://git.io/streak-stats"><img src="https://streak-stats.demolab.com?user=Noxidsoft&theme=tokyonight" alt="GitHub Streak" /></a>
![GitHub Summary](http://github-profile-summary-cards.vercel.app/api/cards/profile-details?username=Noxidsoft&theme=tokyonight)`

**Comment by noxidsoft** [comment]
You are right, it was well documented too, thanks for the heads up.

**Comment by abdulsamad2708** [comment]
> Only this seems to work. If I add any other parameters it fails: `<a href="https://git.io/streak-stats"><img src="https://streak-stats.demolab.com?user=Noxidsoft&theme=tokyonight" alt="GitHub Streak" /></a>`

This worked for me
It takes some time to load initially but once it loads on the web you can get it loaded on your profile
Only issue I am facing is that when I try to hide borders it gives an error again but border isn't an issue for me
