### ISSUE TITLE
Fix color of dropdown arrows on demo site in dark mode

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-streak-stats#75]
**Describe the bug**

On Dark Mode on the [Demo Site](https://github-readme-streak-stats.herokuapp.com/demo/), the arrows are difficult to see since they are black on a dark background.

**To Reproduce**

1. Go to https://github-readme-streak-stats.herokuapp.com/demo/
2. Click on the dark mode toggle
4. See the color of the dropdown arrows

**Expected behavior**

Black arrows on light mode and white arrows on dark mode

**Screenshots**

![image](https://user-images.githubusercontent.com/20955511/114636057-cf4c1d00-9cce-11eb-8568-ee029ddb70f1.png)

![image](https://user-images.githubusercontent.com/20955511/114636061-d1ae7700-9cce-11eb-9334-cbde77d9d6e2.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Brave, Firefox
 - Version: Brave 1.22.71 Chromium 89.0.4389.114

**Additional context**

The color of the arrow is set in the CSS, so the solution may involve changing this part:

![image](https://user-images.githubusercontent.com/20955511/114636346-6dd87e00-9ccf-11eb-9399-173d7791a18b.png)

**Comment by vikasganiga05** [comment]
Hi, I like to work on this issue.
