### ISSUE TITLE
Not displaying stats on profile

### ISSUE THREAD

**Issue by Arcron-ArchLinux** [DenverCoder1/github-readme-streak-stats#751]
**Describe the bug**
Well when I created my github stats from this repo with the steps shown it worked for the first 2 days but then today it is showing it when I visit the URL in a new tab but in my README profile it is not showing the stats.

**Expected behavior**
I expected that this would still be normal and show my stats but it was not showing.

**Screenshots**
![Screenshot_20241217_200010](https://github.com/user-attachments/assets/91e21077-e231-4001-880b-86edc40058da)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser Brave
- Version latest

can anybody tell me that the server is down or is this a bug?

**Comment by pjmartorell** [comment]
https://github.com/DenverCoder1/github-readme-streak-stats/issues/733#issuecomment-2494464170
