### ISSUE TITLE
📝 Fix broken links in README.md

### ISSUE THREAD

**Issue by vikasganiga05** [DenverCoder1/github-readme-streak-stats#81]
The link to run the project locally & the link to run the demo site locally are not correct. Both are missing the `src` directory.

#### How to Fix :

```diff
- http://localhost:8000/?user=DenverCoder1
+ http://localhost:8000/src/?user=DenverCoder1
```
```diff
- http://localhost:8000/demo/
+ http://localhost:8000/src/demo/
```

#### Screenshot : 

![image](https://user-images.githubusercontent.com/74750414/114953789-ca29d200-9e76-11eb-8e09-3d02ee6dbda3.png)

**Comment by DenverCoder1** [comment]
The `composer start` script is set to run `php -S localhost:8000 -t src` which will set `src` as the root directory, so if you use this new script, the /src/ is not part of the url any more.

**Comment by vikasganiga05** [comment]
> The `composer start` script is set to run `php -S localhost:8000 -t src` which will set `src` as the root directory, so if you use this new script, the /src/ is not part of the url any more.

Oh! sorry, my bad. I didn't notice that.
